-- ══════════════════════════════════════════════════════════════
-- 011 — Seed recettes : ~70 recettes (rubs, marinades, mops, injections, glazes)
-- Sources : Aaron Franklin, Meathead Goldwyn, Myron Mixon, Tuffy Stone,
-- Malcolm Reed, competitions KCBS/FBA, Reddit r/smoking, traditions mondiales
-- ══════════════════════════════════════════════════════════════

DELETE FROM recipes;

INSERT INTO recipes (title, slug, type, summary, description, ingredients, steps, yield_amount, prep_time, meat_types, origin, difficulty, tags, status, sort_order) VALUES

-- ═══════════════════════════════════════════════════════════
-- RUBS (50)
-- ═══════════════════════════════════════════════════════════

-- ── Texas & Boeuf ──

('Dalmatian Rub (Texas Style)', 'dalmatian-rub-texas', 'rub',
 'Le rub minimaliste texan. 50/50 sel + poivre. Laisse le boeuf et la fumée parler.',
 'Le Dalmatian rub est LA base du BBQ texan, popularisé par Aaron Franklin. Ratio 50/50 sel kosher et poivre noir 16 mesh (mouture café). La clé : poivre fraîchement concassé.',
 '[{"name":"Sel kosher (Morton)","qty":"60g"},{"name":"Poivre noir 16 mesh","qty":"60g","note":"Concassé gros, pas moulu fin"}]',
 '["Mélanger sel et poivre.","Appliquer généreusement 30-40 min avant cuisson.","Saupoudrer d''en haut, ne pas masser."]',
 '120g — 1 brisket', '2 min', '{brisket,beef_short_ribs}', 'Aaron Franklin — Austin, TX', 'facile',
 '{texas,brisket,sel-poivre,franklin,minimaliste}', 'published', 1),

('Dalmatian+ (SPG)', 'dalmatian-plus-spg', 'rub',
 'La version améliorée : sel, poivre, ail granulé. Le trio magique pour tout le boeuf.',
 'SPG = Salt, Pepper, Garlic. Beaucoup de pitmasters texans ajoutent de l''ail granulé au Dalmatian classique pour une couche de saveur en plus. Ratio classique : 2:2:1.',
 '[{"name":"Sel kosher","qty":"50g"},{"name":"Poivre noir concassé","qty":"50g"},{"name":"Ail granulé","qty":"25g"}]',
 '["Mélanger les 3 ingrédients.","Appliquer comme le Dalmatian classique."]',
 '125g — 1 brisket', '2 min', '{brisket,beef_short_ribs,tomahawk,prime_rib}', 'Texas — variante populaire', 'facile',
 '{texas,SPG,boeuf,ail}', 'published', 2),

('Santa Maria Rub', 'santa-maria-rub', 'rub',
 'Le rub californien classique : sel, poivre, ail, persil séché. Tradition des ranchs de Santa Maria.',
 'Originaire de la Santa Maria Valley en Californie, ce rub simple est la base du tri-tip grillé au feu de chêne rouge. Le persil séché apporte une note herbacée subtile.',
 '[{"name":"Sel kosher","qty":"40g"},{"name":"Poivre noir","qty":"30g"},{"name":"Ail granulé","qty":"20g"},{"name":"Persil séché","qty":"10g"},{"name":"Cayenne","qty":"2g","note":"Optionnel"}]',
 '["Mélanger tous les ingrédients.","Appliquer 1h avant cuisson.","Idéal sur tri-tip grillé au charbon de chêne."]',
 '100g', '2 min', '{brisket,tomahawk,chuck_roast}', 'Santa Maria Valley, Californie', 'facile',
 '{california,santa-maria,tri-tip,ail}', 'published', 3),

('Espresso-Ancho Rub', 'espresso-ancho-rub', 'rub',
 'Café espresso, piment ancho et cacao. Bark sombre, saveur profonde et complexe.',
 'Le café moulu crée une bark presque noire et apporte de l''amertume qui contraste avec le gras du boeuf. Le piment ancho donne un piquant doux et fumé. Le cacao renforce la profondeur. Inspiré de Tuffy Stone.',
 '[{"name":"Café espresso moulu fin","qty":"25g"},{"name":"Piment ancho en poudre","qty":"20g"},{"name":"Poivre noir","qty":"20g"},{"name":"Sel kosher","qty":"25g"},{"name":"Cacao non sucré","qty":"10g"},{"name":"Poudre d''ail","qty":"10g"},{"name":"Cassonade","qty":"15g"},{"name":"Cumin","qty":"5g"}]',
 '["Mélanger toutes les épices.","Appliquer sur viande à température ambiante.","Attention : le café et le sucre brûlent vite au-dessus de 175°C."]',
 '130g', '5 min', '{brisket,beef_short_ribs,chuck_roast,tomahawk}', 'Tuffy Stone — Cool Smoke', 'moyen',
 '{café,espresso,ancho,cacao,bark}', 'published', 4),

('Montreal Steak Spice', 'montreal-steak-spice', 'rub',
 'Le classique canadien. Poivre concassé, ail, coriandre, aneth, flocons de piment.',
 'Créé dans les delis de Montréal (Schwartz''s), ce mélange est devenu un standard nord-américain pour le steak. Le secret : du poivre noir ET des flocons de piment rouge pour une double couche de chaleur.',
 '[{"name":"Poivre noir concassé","qty":"25g"},{"name":"Sel kosher","qty":"20g"},{"name":"Ail déshydraté","qty":"15g"},{"name":"Coriandre moulue","qty":"10g"},{"name":"Aneth séché","qty":"10g"},{"name":"Flocons de piment rouge","qty":"8g"},{"name":"Poudre d''oignon","qty":"8g"},{"name":"Paprika","qty":"5g"}]',
 '["Mélanger tous les ingrédients.","Presser fermement sur les steaks.","Laisser 20-30 min avant cuisson."]',
 '100g', '3 min', '{tomahawk,prime_rib,beef_short_ribs}', 'Montréal, Canada', 'facile',
 '{montréal,steak,canadien,poivre}', 'published', 5),

('Cocoa Chili Rub', 'cocoa-chili-rub', 'rub',
 'Cacao, chili et cannelle. Un rub mexicain profond pour le boeuf fumé.',
 'Inspiré du mole mexicain, ce rub apporte des notes chocolatées et épicées. La cannelle et le cumin rappellent les saveurs d''Oaxaca. Spectaculaire sur des short ribs fumées.',
 '[{"name":"Cacao non sucré","qty":"20g"},{"name":"Chili powder","qty":"20g"},{"name":"Sel kosher","qty":"20g"},{"name":"Poivre noir","qty":"10g"},{"name":"Cumin","qty":"10g"},{"name":"Cannelle","qty":"5g"},{"name":"Poudre d''ail","qty":"10g"},{"name":"Cassonade","qty":"15g"},{"name":"Cayenne","qty":"3g"}]',
 '["Mélanger tous les ingrédients.","Appliquer sur viande sèche.","Laisser reposer 1h avant fumage."]',
 '130g', '5 min', '{beef_short_ribs,brisket,chuck_roast}', 'Inspiration mexicaine / mole', 'moyen',
 '{cacao,chili,mexicain,mole,cannelle}', 'published', 6),

('Rub au Raifort & Moutarde', 'rub-raifort-moutarde', 'rub',
 'Moutarde sèche, raifort en poudre et poivre. Piquant et vif pour le boeuf.',
 'Le raifort en poudre donne un piquant nasal unique qui se marie parfaitement avec le gras du boeuf. La moutarde sèche renforce cette chaleur. Parfait pour un prime rib ou un rosbif fumé.',
 '[{"name":"Moutarde sèche","qty":"20g"},{"name":"Raifort en poudre","qty":"15g"},{"name":"Poivre noir","qty":"20g"},{"name":"Sel kosher","qty":"25g"},{"name":"Poudre d''ail","qty":"10g"},{"name":"Thym séché","qty":"5g"},{"name":"Poudre d''oignon","qty":"10g"}]',
 '["Mélanger tous les ingrédients.","Appliquer en couche fine — c''est puissant.","Idéal pour le prime rib ou rosbif."]',
 '105g', '3 min', '{prime_rib,brisket,tomahawk}', 'Tradition britannique / BBQ US', 'facile',
 '{raifort,moutarde,boeuf,piquant}', 'published', 7),

('Steakhouse Rub', 'steakhouse-rub', 'rub',
 'Le rub des grands steakhouses : ail, oignon, paprika fumé, herbes sèches. Classique et fiable.',
 'Ce rub reproduit les saveurs des meilleurs steakhouses américains. Le paprika fumé apporte la couleur, les herbes sèches la complexité. Fonctionne sur tout type de steak.',
 '[{"name":"Sel kosher","qty":"25g"},{"name":"Poivre noir","qty":"20g"},{"name":"Paprika fumé","qty":"15g"},{"name":"Poudre d''ail","qty":"15g"},{"name":"Poudre d''oignon","qty":"10g"},{"name":"Origan séché","qty":"5g"},{"name":"Thym séché","qty":"5g"},{"name":"Cayenne","qty":"2g"}]',
 '["Mélanger toutes les épices.","Assaisonner les steaks des deux côtés.","Repos 15-30 min à température ambiante."]',
 '100g', '3 min', '{tomahawk,prime_rib,beef_short_ribs}', 'Steakhouses américains', 'facile',
 '{steakhouse,steak,classique,herbes}', 'published', 8),

-- ── Porc ──

('Memphis Dust', 'memphis-dust', 'rub',
 'Le rub sucré légendaire de Meathead. Cassonade, paprika, gingembre. LE rub pour le porc.',
 'Créé par Meathead Goldwyn (AmazingRibs.com), probablement le rub maison le plus reproduit au monde. Base sucrée pour une bark caramélisée. Pas de sel — saler séparément (½ c.à.c sel/livre, 12h avant).',
 '[{"name":"Cassonade foncée","qty":"110g"},{"name":"Sucre blanc","qty":"110g"},{"name":"Paprika","qty":"60g"},{"name":"Poudre d''ail","qty":"30g"},{"name":"Poivre noir","qty":"15g"},{"name":"Gingembre moulu","qty":"15g"},{"name":"Poudre d''oignon","qty":"15g"},{"name":"Romarin en poudre","qty":"8g"}]',
 '["Mélanger, casser les grumeaux de cassonade.","Stocker dans un contenant hermétique (3 mois).","Humidifier la viande, saupoudrer sans trop charger.","Saler séparément la veille."]',
 '350g — 4-5 cuissons', '5 min', '{pulled_pork,spare_ribs,baby_back_ribs,whole_chicken}', 'Meathead Goldwyn — AmazingRibs.com', 'facile',
 '{memphis,sucré,porc,ribs,meathead}', 'published', 10),

('Sweet Heat Rib Rub', 'sweet-heat-rib-rub', 'rub',
 'Sucré-piquant : cassonade, chipotle, cannelle. Le rub de compétition pour des ribs gagnantes.',
 'Inspiré de Myron Mixon (5x champion du monde). Équilibre sucré/piquant. La cassonade caramélise, le chipotle apporte un piquant fumé, la cannelle une chaleur douce.',
 '[{"name":"Cassonade foncée","qty":"80g"},{"name":"Paprika","qty":"30g"},{"name":"Poivre noir","qty":"15g"},{"name":"Poudre d''ail","qty":"15g"},{"name":"Chipotle en poudre","qty":"12g"},{"name":"Poudre d''oignon","qty":"10g"},{"name":"Sel kosher","qty":"25g"},{"name":"Cannelle","qty":"5g"},{"name":"Cayenne","qty":"5g"},{"name":"Moutarde sèche","qty":"5g"}]',
 '["Mélanger, écraser les grumeaux.","Retirer la membrane des ribs.","Binder (moutarde jaune), puis rub des deux côtés.","30 min de repos avant cuisson."]',
 '200g — 3 racks', '5 min', '{spare_ribs,baby_back_ribs}', 'Inspiré de Myron Mixon', 'facile',
 '{ribs,sucré,piquant,compétition,mixon}', 'published', 11),

('Apple Cinnamon Pork Rub', 'apple-cinnamon-pork-rub', 'rub',
 'Doux et automnal : pomme déshydratée, cannelle, muscade. Parfait pour le pulled pork.',
 'Un rub original qui joue sur l''accord classique porc-pomme. La poudre de pomme déshydratée apporte une douceur fruitée unique. La cannelle et la muscade complètent le profil automnal.',
 '[{"name":"Cassonade","qty":"60g"},{"name":"Paprika fumé","qty":"25g"},{"name":"Poudre de pomme déshydratée","qty":"20g","note":"Ou jus de pomme en poudre"},{"name":"Sel kosher","qty":"20g"},{"name":"Cannelle","qty":"8g"},{"name":"Poudre d''ail","qty":"10g"},{"name":"Muscade","qty":"3g"},{"name":"Piment de la Jamaïque","qty":"3g"},{"name":"Poivre noir","qty":"10g"}]',
 '["Mélanger toutes les épices.","Appliquer sur pork butt la veille.","Le bois de pommier se marie idéalement."]',
 '160g', '5 min', '{pulled_pork,spare_ribs,baby_back_ribs}', 'Pitmaster communauté r/smoking', 'facile',
 '{pomme,cannelle,automne,porc}', 'published', 12),

('Honey Garlic Rub', 'honey-garlic-rub', 'rub',
 'Miel en poudre et ail rôti. Un rub doux et doré pour les ribs et le poulet.',
 'Le miel en poudre (ou granulé) remplace le sucre classique et apporte une saveur plus complexe. L''ail en grande quantité donne un profil savoureux. Inspiré du Killer Bee de Kosmos Q.',
 '[{"name":"Miel en poudre","qty":"40g"},{"name":"Poudre d''ail","qty":"25g"},{"name":"Paprika","qty":"20g"},{"name":"Sel kosher","qty":"20g"},{"name":"Poivre noir","qty":"15g"},{"name":"Poudre d''oignon","qty":"10g"},{"name":"Curcuma","qty":"5g","note":"Pour la couleur dorée"},{"name":"Cayenne","qty":"3g"}]',
 '["Mélanger tous les ingrédients.","Appliquer sur viande légèrement huilée.","Le curcuma aide à la couleur — ne pas trop en mettre."]',
 '140g', '3 min', '{baby_back_ribs,spare_ribs,whole_chicken}', 'Inspiré de Kosmos Q Killer Bee', 'facile',
 '{miel,ail,doré,ribs,poulet}', 'published', 13),

('Mustard Seed Pork Rub', 'mustard-seed-pork-rub', 'rub',
 'Graines de moutarde concassées, cassonade et poivre. Style Carolina pour le pulled pork.',
 'En Caroline du Sud, la moutarde est reine. Ce rub utilise des graines de moutarde jaune concassées pour un piquant naturel et une texture croquante dans la bark.',
 '[{"name":"Graines de moutarde jaune concassées","qty":"25g"},{"name":"Cassonade","qty":"40g"},{"name":"Paprika","qty":"20g"},{"name":"Sel kosher","qty":"20g"},{"name":"Poivre noir","qty":"15g"},{"name":"Moutarde sèche","qty":"10g"},{"name":"Poudre d''ail","qty":"10g"},{"name":"Cumin","qty":"5g"},{"name":"Cayenne","qty":"3g"}]',
 '["Concasser les graines de moutarde au mortier (pas trop fin).","Mélanger avec les autres épices.","Binder à la moutarde jaune, puis appliquer le rub."]',
 '150g', '5 min', '{pulled_pork,spare_ribs}', 'Caroline du Sud', 'moyen',
 '{moutarde,carolina,porc,graines}', 'published', 14),

('Jerk Dry Rub', 'jerk-dry-rub', 'rub',
 'Version sèche du jerk jamaïcain. Piment de la Jamaïque, scotch bonnet, thym, muscade.',
 'Pour ceux qui préfèrent un rub sec plutôt qu''une marinade humide. Le piment de la Jamaïque (allspice) est L''ingrédient clé du jerk. Le scotch bonnet en poudre apporte le feu.',
 '[{"name":"Piment de la Jamaïque (allspice)","qty":"20g"},{"name":"Thym séché","qty":"15g"},{"name":"Cassonade","qty":"25g"},{"name":"Sel kosher","qty":"15g"},{"name":"Poivre noir","qty":"10g"},{"name":"Ail en poudre","qty":"10g"},{"name":"Oignon en poudre","qty":"10g"},{"name":"Scotch bonnet en poudre","qty":"5g","note":"Ou habanero"},{"name":"Cannelle","qty":"3g"},{"name":"Muscade","qty":"3g"},{"name":"Gingembre","qty":"5g"}]',
 '["Mélanger toutes les épices.","Masser la viande généreusement.","Laisser reposer 2-4h au frigo.","Fumage au bois de cerisier ou pommier."]',
 '120g', '5 min', '{whole_chicken,spare_ribs,pulled_pork}', 'Jamaïque', 'moyen',
 '{jerk,jamaïque,épicé,allspice}', 'published', 15),

('Brown Sugar Bourbon Rub', 'brown-sugar-bourbon-rub', 'rub',
 'Cassonade, poudre de bourbon et vanille. Riche et caramélisé pour les ribs.',
 'La poudre de bourbon (bourbon en poudre, trouvable en ligne) apporte les notes de vanille et de chêne sans l''humidité. Sinon, ajouter un trait de bourbon dans le binder.',
 '[{"name":"Cassonade foncée","qty":"80g"},{"name":"Paprika fumé","qty":"20g"},{"name":"Sel kosher","qty":"20g"},{"name":"Poivre noir","qty":"15g"},{"name":"Poudre d''ail","qty":"15g"},{"name":"Poudre de bourbon","qty":"10g","note":"Ou vanille en poudre"},{"name":"Poudre d''oignon","qty":"10g"},{"name":"Cayenne","qty":"3g"}]',
 '["Mélanger soigneusement.","Pour les ribs : binder au bourbon + moutarde.","Appliquer le rub, repos 30-45 min."]',
 '170g', '5 min', '{spare_ribs,baby_back_ribs,pulled_pork}', 'Sud des États-Unis', 'facile',
 '{bourbon,cassonade,vanille,ribs}', 'published', 16),

('Kansas City Sweet Rub', 'kansas-city-sweet-rub', 'rub',
 'Le style KC : très sucré, tomate, paprika. Base pour le BBQ sauce-forward de Kansas City.',
 'Kansas City est connue pour son BBQ sucré et saucé. Ce rub est la base — il crée une bark sucrée qui se marie avec le glaçage de sauce BBQ final.',
 '[{"name":"Cassonade","qty":"80g"},{"name":"Paprika","qty":"40g"},{"name":"Sel kosher","qty":"20g"},{"name":"Chili powder","qty":"15g"},{"name":"Poivre noir","qty":"10g"},{"name":"Poudre d''ail","qty":"15g"},{"name":"Poudre d''oignon","qty":"10g"},{"name":"Cumin","qty":"5g"},{"name":"Moutarde sèche","qty":"5g"}]',
 '["Mélanger toutes les épices.","Appliquer généreusement sur ribs ou porc.","En fin de cuisson, glacer avec sauce BBQ KC."]',
 '200g', '3 min', '{spare_ribs,baby_back_ribs,pulled_pork}', 'Kansas City, Missouri', 'facile',
 '{kansas-city,sucré,sauce,KC}', 'published', 17),

('Carolina Gold Rub', 'carolina-gold-rub', 'rub',
 'Curcuma, moutarde et vinaigre en poudre. Le rub doré de la Caroline du Sud.',
 'La Caroline du Sud est célèbre pour sa sauce moutarde dorée. Ce rub sec reprend ces saveurs : curcuma pour la couleur, moutarde pour le piquant, vinaigre en poudre pour l''acidité.',
 '[{"name":"Moutarde sèche","qty":"25g"},{"name":"Curcuma","qty":"15g"},{"name":"Cassonade","qty":"30g"},{"name":"Paprika","qty":"20g"},{"name":"Sel kosher","qty":"20g"},{"name":"Poivre noir","qty":"10g"},{"name":"Poudre d''ail","qty":"10g"},{"name":"Vinaigre en poudre","qty":"10g","note":"Maltodextrine + vinaigre"},{"name":"Cayenne","qty":"3g"}]',
 '["Mélanger tous les ingrédients.","Appliquer sur pulled pork ou ribs.","Se marie avec une sauce moutarde en finition."]',
 '140g', '3 min', '{pulled_pork,spare_ribs}', 'Caroline du Sud', 'facile',
 '{carolina,moutarde,doré,curcuma}', 'published', 18),

-- ── Volaille ──

('Lemon Pepper Rub', 'lemon-pepper-rub', 'rub',
 'Citron et poivre concassé. Frais et vif, le meilleur ami du poulet.',
 'Le lemon pepper est un classique américain pour le poulet. Le zeste de citron déshydraté apporte la fraîcheur, le poivre concassé le piquant. Simple et efficace.',
 '[{"name":"Zeste de citron déshydraté","qty":"25g","note":"Ou zeste frais séché au four"},{"name":"Poivre noir concassé","qty":"25g"},{"name":"Sel kosher","qty":"20g"},{"name":"Poudre d''ail","qty":"10g"},{"name":"Poudre d''oignon","qty":"10g"},{"name":"Thym séché","qty":"5g"}]',
 '["Mélanger tous les ingrédients.","Appliquer sous et sur la peau du poulet.","Idéal avec du bois de cerisier."]',
 '95g', '3 min', '{whole_chicken}', 'Classique américain', 'facile',
 '{citron,poivre,poulet,frais}', 'published', 20),

('Herbes de Provence Rub', 'herbes-de-provence-rub', 'rub',
 'Thym, romarin, lavande, sarriette. Le rub provençal pour le poulet et l''agneau.',
 'Les herbes de Provence apportent un parfum méditerranéen magnifique au fumoir. La lavande est optionnelle mais donne une touche unique. Excellent sur poulet entier ou gigot.',
 '[{"name":"Thym séché","qty":"15g"},{"name":"Romarin séché","qty":"15g"},{"name":"Sarriette séchée","qty":"10g"},{"name":"Origan séché","qty":"10g"},{"name":"Lavande séchée","qty":"3g","note":"Optionnel — très peu"},{"name":"Sel kosher","qty":"20g"},{"name":"Poivre noir","qty":"10g"},{"name":"Poudre d''ail","qty":"10g"}]',
 '["Mélanger les herbes et épices.","Frotter le poulet avec huile d''olive + rub.","Appliquer aussi à l''intérieur de la cavité."]',
 '90g', '3 min', '{whole_chicken}', 'Provence, France', 'facile',
 '{herbes,provence,méditerranée,lavande,poulet}', 'published', 21),

('Tandoori Rub', 'tandoori-rub', 'rub',
 'Cumin, coriandre, curcuma, garam masala, gingembre. Le rub indien pour un poulet fumé épicé.',
 'Inspiré de la cuisine tandoori, ce rub fonctionne aussi bien au fumoir qu''au four. Le garam masala apporte la complexité. Le curcuma la couleur. Mélanger avec du yaourt pour un binder parfait.',
 '[{"name":"Cumin moulu","qty":"15g"},{"name":"Coriandre moulue","qty":"15g"},{"name":"Curcuma","qty":"10g"},{"name":"Garam masala","qty":"10g"},{"name":"Paprika","qty":"15g"},{"name":"Gingembre moulu","qty":"8g"},{"name":"Poudre d''ail","qty":"10g"},{"name":"Sel kosher","qty":"15g"},{"name":"Cayenne","qty":"5g"},{"name":"Cannelle","qty":"3g"}]',
 '["Mélanger toutes les épices.","Binder : yaourt nature + jus de citron.","Mariner 4-12h au frigo.","Fumer à 150°C ou griller."]',
 '110g', '5 min', '{whole_chicken}', 'Inde — adapté BBQ', 'moyen',
 '{tandoori,indien,épicé,yaourt}', 'published', 22),

('Shawarma Rub', 'shawarma-rub', 'rub',
 'Cumin, paprika, curcuma, cardamome, clou de girofle. Le rub du Moyen-Orient.',
 'Le shawarma est un classique de street food. Ce rub sec capture ses saveurs : chaud, terreux, légèrement sucré. Parfait pour le poulet grillé en brochettes ou entier au fumoir.',
 '[{"name":"Cumin moulu","qty":"15g"},{"name":"Paprika","qty":"15g"},{"name":"Curcuma","qty":"10g"},{"name":"Coriandre moulue","qty":"10g"},{"name":"Cannelle","qty":"5g"},{"name":"Cardamome moulue","qty":"3g"},{"name":"Clou de girofle moulu","qty":"2g"},{"name":"Sel kosher","qty":"15g"},{"name":"Poivre noir","qty":"8g"},{"name":"Poudre d''ail","qty":"10g"},{"name":"Cayenne","qty":"3g"}]',
 '["Mélanger toutes les épices.","Masser le poulet avec huile + rub.","Mariner 2-4h minimum.","Griller en brochettes ou fumer entier."]',
 '100g', '5 min', '{whole_chicken}', 'Moyen-Orient', 'facile',
 '{shawarma,moyen-orient,épices,brochettes}', 'published', 23),

('Za''atar Rub', 'zaatar-rub', 'rub',
 'Thym, sumac, sésame grillé. Le mélange libanais ancestral adapté au BBQ.',
 'Le za''atar est un mélange d''herbes et d''épices utilisé depuis des millénaires au Moyen-Orient. Le sumac apporte une acidité citronnée unique. Le sésame grillé du croquant.',
 '[{"name":"Thym séché","qty":"20g"},{"name":"Sumac","qty":"20g"},{"name":"Graines de sésame grillées","qty":"15g"},{"name":"Sel kosher","qty":"10g"},{"name":"Origan séché","qty":"10g"}]',
 '["Mélanger tous les ingrédients.","Masser le poulet avec huile d''olive puis za''atar.","Excellent aussi en finition après cuisson."]',
 '75g', '2 min', '{whole_chicken}', 'Liban / Moyen-Orient', 'facile',
 '{zaatar,libanais,sumac,sésame,herbes}', 'published', 24),

('Cajun Fumé', 'rub-cajun-fume', 'rub',
 'Paprika fumé, cayenne, thym, origan. La chaleur louisianaise au fumoir.',
 'Le paprika fumé (pimentón de la Vera) renforce le goût de fumée. Le cayenne est dosé pour piquer sans brûler. Excellent sur le poulet entier ou les cuisses.',
 '[{"name":"Paprika fumé","qty":"30g"},{"name":"Sel kosher","qty":"25g"},{"name":"Poudre d''ail","qty":"20g"},{"name":"Poivre noir","qty":"15g"},{"name":"Poudre d''oignon","qty":"15g"},{"name":"Cayenne","qty":"8g"},{"name":"Thym séché","qty":"8g"},{"name":"Origan séché","qty":"8g"},{"name":"Moutarde sèche","qty":"5g"}]',
 '["Combiner tous les ingrédients.","Poulet : sous et sur la peau.","Porc : 2-4h avant cuisson."]',
 '150g', '5 min', '{whole_chicken,pulled_pork,spare_ribs}', 'Louisiane', 'facile',
 '{cajun,épicé,fumé,louisiane}', 'published', 25),

('Greek Souvlaki Rub', 'greek-souvlaki-rub', 'rub',
 'Origan, ail, citron séché. Le rub grec sec pour brochettes et poulet grillé.',
 'L''origan grec séché est plus aromatique que l''origan ordinaire. Combiné avec du zeste de citron et de l''ail, c''est la base du souvlaki parfait.',
 '[{"name":"Origan grec séché","qty":"20g"},{"name":"Zeste de citron séché","qty":"15g"},{"name":"Poudre d''ail","qty":"15g"},{"name":"Sel kosher","qty":"15g"},{"name":"Poivre noir","qty":"10g"},{"name":"Poudre d''oignon","qty":"10g"},{"name":"Paprika","qty":"5g"}]',
 '["Mélanger les ingrédients.","Couper le poulet en cubes, huiler.","Saupoudrer généreusement et enfiler en brochettes."]',
 '90g', '3 min', '{whole_chicken}', 'Grèce', 'facile',
 '{grec,souvlaki,origan,brochettes}', 'published', 26),

-- ── Polyvalents ──

('Rub All-Purpose Charbon & Flamme', 'rub-charbon-flamme', 'rub',
 'Notre rub maison polyvalent. Boeuf, porc, volaille — il va sur tout.',
 'Un rub pensé pour le quotidien du pitmaster. Pas trop sucré pour le boeuf, pas trop salé pour le porc, assez parfumé pour le poulet.',
 '[{"name":"Paprika fumé","qty":"30g"},{"name":"Sel kosher","qty":"25g"},{"name":"Poivre noir","qty":"20g"},{"name":"Cassonade","qty":"20g"},{"name":"Poudre d''ail","qty":"15g"},{"name":"Poudre d''oignon","qty":"15g"},{"name":"Cumin","qty":"8g"},{"name":"Moutarde sèche","qty":"5g"},{"name":"Cayenne","qty":"3g"}]',
 '["Mélanger et stocker.","Boeuf : 1h avant. Porc : veille. Poulet : sous la peau, 1h avant."]',
 '160g', '3 min', '{brisket,pulled_pork,spare_ribs,whole_chicken,chuck_roast}', 'Charbon & Flamme — Original', 'facile',
 '{polyvalent,maison,all-purpose}', 'published', 30),

('Five Pepper Rub', 'five-pepper-rub', 'rub',
 'Cinq poivres : noir, blanc, vert, rose, Sichuan. Pour les amateurs de poivre.',
 'Ce rub met le poivre à l''honneur sous toutes ses formes. Le Sichuan apporte un engourdissement unique, le rose une douceur florale, le vert de la fraîcheur. Spectaculaire sur un steak.',
 '[{"name":"Poivre noir concassé","qty":"15g"},{"name":"Poivre blanc moulu","qty":"10g"},{"name":"Poivre vert lyophilisé","qty":"5g"},{"name":"Baies roses","qty":"5g"},{"name":"Poivre de Sichuan","qty":"5g"},{"name":"Sel kosher","qty":"25g"},{"name":"Poudre d''ail","qty":"10g"}]',
 '["Concasser grossièrement les 5 poivres au mortier.","Mélanger avec sel et ail.","Appliquer sur steaks ou brisket."]',
 '75g', '5 min', '{tomahawk,prime_rib,brisket,beef_short_ribs}', 'Inspiration gastronomique', 'moyen',
 '{cinq-poivres,poivre,sichuan,gastronomique}', 'published', 31),

('Ras el Hanout BBQ', 'ras-el-hanout-bbq', 'rub',
 'Le mélange marocain royal adapté au BBQ. Cumin, cardamome, rose, muscade.',
 'Ras el Hanout signifie "tête de la boutique" — le meilleur mélange du marchand. Des dizaines d''épices possibles, mais cette version est optimisée pour le fumoir.',
 '[{"name":"Cumin moulu","qty":"12g"},{"name":"Coriandre moulue","qty":"10g"},{"name":"Paprika","qty":"12g"},{"name":"Curcuma","qty":"8g"},{"name":"Cannelle","qty":"5g"},{"name":"Gingembre moulu","qty":"5g"},{"name":"Cardamome","qty":"3g"},{"name":"Clou de girofle","qty":"2g"},{"name":"Muscade","qty":"2g"},{"name":"Pétales de rose séchés","qty":"3g","note":"Optionnel"},{"name":"Sel kosher","qty":"15g"},{"name":"Poivre noir","qty":"8g"}]',
 '["Mélanger toutes les épices.","Parfait sur agneau, poulet ou légumes grillés.","Appliquer avec huile d''olive comme binder."]',
 '85g', '5 min', '{whole_chicken,pulled_pork}', 'Maroc', 'moyen',
 '{marocain,ras-el-hanout,épices,agneau}', 'published', 32),

('Piri Piri Rub', 'piri-piri-rub', 'rub',
 'Le rub portugais/africain épicé. Piri piri, paprika fumé, citron, ail.',
 'Le piri piri (ou peri peri) est un piment petit mais puissant d''Afrique. Ce rub sec capture l''esprit du poulet grillé de Nando''s et des churrasqueiras portugaises.',
 '[{"name":"Paprika fumé","qty":"20g"},{"name":"Piri piri en poudre","qty":"10g","note":"Ou bird''s eye chili"},{"name":"Sel kosher","qty":"15g"},{"name":"Poudre d''ail","qty":"15g"},{"name":"Poudre d''oignon","qty":"10g"},{"name":"Zeste de citron séché","qty":"10g"},{"name":"Origan séché","qty":"8g"},{"name":"Poivre noir","qty":"8g"}]',
 '["Mélanger toutes les épices.","Masser le poulet avec huile + rub.","Mariner 2-4h au frigo."]',
 '100g', '5 min', '{whole_chicken}', 'Portugal / Afrique', 'moyen',
 '{piri-piri,portugais,épicé,poulet}', 'published', 33),

('Togarashi BBQ Rub', 'togarashi-bbq-rub', 'rub',
 'Le shichimi togarashi japonais adapté au fumoir. Sésame, nori, Sichuan, agrumes.',
 'Le togarashi est un mélange japonais de 7 épices. Cette version BBQ ajoute du sel et de l''ail pour un rub complet. Incroyable sur du poulet ou des côtes de porc.',
 '[{"name":"Flocons de piment rouge","qty":"10g"},{"name":"Graines de sésame grillées","qty":"10g"},{"name":"Zeste d''orange séché","qty":"8g"},{"name":"Nori en poudre","qty":"5g","note":"Algue séchée mixée"},{"name":"Poivre de Sichuan","qty":"5g"},{"name":"Graines de pavot","qty":"5g"},{"name":"Gingembre moulu","qty":"5g"},{"name":"Sel kosher","qty":"15g"},{"name":"Poudre d''ail","qty":"10g"}]',
 '["Mélanger tous les ingrédients.","Appliquer légèrement — les saveurs sont concentrées.","Excellent sur poulet yakitori ou côtes de porc."]',
 '75g', '5 min', '{whole_chicken,spare_ribs,baby_back_ribs}', 'Japon — adapté BBQ', 'moyen',
 '{japonais,togarashi,sésame,nori,fusion}', 'published', 34),

('Berbere Rub', 'berbere-rub', 'rub',
 'Le mélange éthiopien épicé : fenugrec, cardamome, piment, gingembre.',
 'Le berbere est le pilier de la cuisine éthiopienne. Complex, chaud et légèrement amer grâce au fenugrec. Excellent sur viande grillée.',
 '[{"name":"Paprika","qty":"20g"},{"name":"Piment rouge en poudre","qty":"10g"},{"name":"Coriandre moulue","qty":"8g"},{"name":"Gingembre moulu","qty":"8g"},{"name":"Fenugrec moulu","qty":"5g"},{"name":"Cardamome","qty":"3g"},{"name":"Cannelle","qty":"3g"},{"name":"Clou de girofle","qty":"2g"},{"name":"Piment de la Jamaïque","qty":"2g"},{"name":"Sel kosher","qty":"15g"},{"name":"Poivre noir","qty":"8g"}]',
 '["Mélanger toutes les épices.","Utiliser avec parcimonie — le fenugrec est puissant.","Masser la viande avec un peu d''huile."]',
 '85g', '5 min', '{whole_chicken,pulled_pork,beef_short_ribs}', 'Éthiopie', 'moyen',
 '{éthiopien,berbere,fenugrec,épicé}', 'published', 35),

('Suya Rub', 'suya-rub', 'rub',
 'Le rub nigérian aux cacahuètes. Arachides grillées, gingembre, cayenne. Unique et addictif.',
 'Le suya est le BBQ de rue du Nigeria. Son rub (yaji) est à base de cacahuètes grillées moulues, ce qui le rend complètement unique. Le résultat est croquant, épicé et profondément savoureux.',
 '[{"name":"Cacahuètes grillées moulues","qty":"40g"},{"name":"Paprika","qty":"15g"},{"name":"Gingembre moulu","qty":"10g"},{"name":"Poudre d''ail","qty":"10g"},{"name":"Poudre d''oignon","qty":"10g"},{"name":"Cayenne","qty":"8g"},{"name":"Sel","qty":"10g"},{"name":"Bouillon de boeuf en poudre","qty":"10g","note":"Optionnel, pour l''umami"}]',
 '["Moudre les cacahuètes finement (pas en pâte).","Mélanger avec les épices.","Enfiler la viande en brochettes.","Huiler et saupoudrer généreusement.","Griller sur charbon vif."]',
 '110g', '10 min', '{whole_chicken,beef_short_ribs}', 'Nigeria', 'moyen',
 '{nigérian,suya,cacahuète,brochettes,street-food}', 'published', 36),

('Chimichurri Dry Rub', 'chimichurri-dry-rub', 'rub',
 'La version sèche du chimichurri. Persil séché, origan, ail, flocons de piment.',
 'Pour ceux qui veulent les saveurs du chimichurri sans l''humidité. Parfait en rub sec avant cuisson, avec du chimichurri frais en finition.',
 '[{"name":"Persil séché","qty":"20g"},{"name":"Origan séché","qty":"15g"},{"name":"Ail déshydraté","qty":"15g"},{"name":"Flocons de piment rouge","qty":"8g"},{"name":"Sel kosher","qty":"15g"},{"name":"Poivre noir","qty":"10g"},{"name":"Oignon déshydraté","qty":"8g"}]',
 '["Mélanger toutes les herbes et épices.","Appliquer sur steak ou boeuf.","Servir avec chimichurri frais en sauce."]',
 '90g', '3 min', '{tomahawk,brisket,beef_short_ribs}', 'Argentine — adapté dry rub', 'facile',
 '{chimichurri,argentin,persil,sec}', 'published', 37),

('Old Bay BBQ Rub', 'old-bay-bbq-rub', 'rub',
 'Le classique du Maryland enrichi pour le BBQ. Céleri, paprika, moutarde, clou de girofle.',
 'Old Bay est LE seasoning de la côte est US, normalement pour les fruits de mer. Cette version BBQ ajoute du sucre et du poivre pour le fumoir. Incroyable sur les ailes de poulet fumées.',
 '[{"name":"Paprika","qty":"20g"},{"name":"Sel de céleri","qty":"15g"},{"name":"Moutarde sèche","qty":"10g"},{"name":"Poivre noir","qty":"10g"},{"name":"Cassonade","qty":"15g"},{"name":"Gingembre moulu","qty":"5g"},{"name":"Cannelle","qty":"3g"},{"name":"Clou de girofle moulu","qty":"2g"},{"name":"Piment de la Jamaïque","qty":"2g"},{"name":"Cardamome","qty":"2g"},{"name":"Cayenne","qty":"3g"}]',
 '["Mélanger tous les ingrédients.","Appliquer sur poulet, fruits de mer ou porc."]',
 '90g', '5 min', '{whole_chicken,spare_ribs}', 'Maryland, USA', 'facile',
 '{old-bay,maryland,céleri,fruits-de-mer}', 'published', 38),

-- ═══════════════════════════════════════════════════════════
-- MARINADES (20+)
-- ═══════════════════════════════════════════════════════════

('Chimichurri Authentique', 'chimichurri-authentique', 'marinade',
 'Persil, ail, origan, vinaigre de vin rouge, huile d''olive. Le classique argentin pur.',
 'Le vrai chimichurri argentin : pas de cilantro, pas de blender. Tout haché au couteau. Sert à la fois de marinade et de sauce de table pour l''asado (BBQ argentin).',
 '[{"name":"Persil plat frais","qty":"1 gros bouquet (60g)"},{"name":"Ail émincé","qty":"6 gousses"},{"name":"Origan séché","qty":"10g"},{"name":"Vinaigre de vin rouge","qty":"80ml"},{"name":"Huile d''olive extra vierge","qty":"120ml"},{"name":"Flocons de piment rouge","qty":"5g"},{"name":"Sel","qty":"8g"},{"name":"Poivre noir","qty":"3g"}]',
 '["Hacher finement le persil AU COUTEAU (pas au blender).","Émincer l''ail très fin.","Mélanger dans un bol avec l''origan, le piment et le sel.","Ajouter le vinaigre, mélanger.","Verser l''huile d''olive, mélanger.","Laisser reposer minimum 2h à température ambiante.","En marinade : badigeonner la viande 2h avant.","En sauce : servir à côté du steak grillé."]',
 '~300ml', '10 min + 2h repos', '{tomahawk,brisket,beef_short_ribs}', 'Argentine — asado traditionnel', 'facile',
 '{chimichurri,argentin,persil,asado,steak}', 'published', 50),

('Marinade Souvlaki Grec', 'marinade-souvlaki-grec', 'marinade',
 'Huile d''olive, citron, origan, ail. La marinade grecque ancestrale pour brochettes.',
 'Le souvlaki est la street food grecque par excellence. Cette marinade simple transforme n''importe quel poulet ou porc en brochettes mémorables. Servir avec tzatziki.',
 '[{"name":"Huile d''olive","qty":"80ml"},{"name":"Jus de citron frais","qty":"60ml"},{"name":"Origan grec séché","qty":"10g"},{"name":"Ail émincé","qty":"4 gousses"},{"name":"Sel","qty":"8g"},{"name":"Poivre noir","qty":"5g"},{"name":"Paprika","qty":"3g"}]',
 '["Mélanger tous les ingrédients.","Couper la viande en cubes de 3cm.","Mariner au frigo 2-8h dans un sac zip.","Enfiler sur des brochettes.","Griller sur charbon vif 3-4 min par face.","Servir avec tzatziki, pita et oignon rouge."]',
 '~250ml', '5 min + 2-8h', '{whole_chicken}', 'Grèce', 'facile',
 '{grec,souvlaki,brochettes,citron,origan}', 'published', 51),

('Marinade Shawarma', 'marinade-shawarma', 'marinade',
 'Yaourt, cumin, cardamome, curcuma. La marinade du kebab du Moyen-Orient.',
 'Le yaourt attendrit la viande et aide les épices à pénétrer. Le cumin et la cardamome sont les épices signatures du shawarma. Mariner longtemps pour un maximum de saveur.',
 '[{"name":"Yaourt nature","qty":"150g"},{"name":"Huile d''olive","qty":"30ml"},{"name":"Jus de citron","qty":"30ml"},{"name":"Cumin moulu","qty":"10g"},{"name":"Paprika","qty":"10g"},{"name":"Curcuma","qty":"5g"},{"name":"Cardamome moulue","qty":"3g"},{"name":"Cannelle","qty":"3g"},{"name":"Ail émincé","qty":"4 gousses"},{"name":"Sel","qty":"8g"},{"name":"Poivre noir","qty":"5g"}]',
 '["Mélanger yaourt, huile, citron et toutes les épices.","Mariner le poulet 8-24h au frigo.","Griller en brochettes ou en pièce entière.","Servir en sandwich pita avec sauce tahini."]',
 '~300ml', '10 min + 8-24h', '{whole_chicken}', 'Moyen-Orient', 'facile',
 '{shawarma,moyen-orient,yaourt,brochettes}', 'published', 52),

('Marinade Teriyaki Authentique', 'marinade-teriyaki-authentique', 'marinade',
 'Soja, mirin, sake, sucre. Le ratio japonais 2:2:2:1 pour un teriyaki parfait.',
 'Le vrai teriyaki n''est pas un sirop épais — c''est une sauce fine et brillante. Le mirin apporte la douceur, le sake la profondeur, la sauce soja l''umami. Ratio classique 2:2:2:1.',
 '[{"name":"Sauce soja japonaise","qty":"80ml"},{"name":"Mirin","qty":"80ml"},{"name":"Saké de cuisine","qty":"80ml"},{"name":"Sucre","qty":"40g"},{"name":"Gingembre frais râpé","qty":"10g","note":"Optionnel"},{"name":"Ail émincé","qty":"2 gousses","note":"Optionnel"}]',
 '["Combiner soja, mirin, saké et sucre dans une casserole.","Porter à ébullition en remuant.","Réduire et mijoter 10-15 min.","Laisser refroidir avant d''utiliser en marinade.","Mariner le poulet 2-4h.","Pour un glaze : badigeonner en fin de cuisson."]',
 '~300ml', '20 min + 2-4h', '{whole_chicken,spare_ribs}', 'Japon', 'facile',
 '{teriyaki,japonais,soja,mirin,umami}', 'published', 53),

('Marinade Al Pastor', 'marinade-al-pastor', 'marinade',
 'Achiote, chiles guajillo, ananas, vinaigre. La marinade mexicaine rouge et fumée.',
 'Le al pastor est né de la fusion libano-mexicaine. L''achiote donne la couleur rouge-orange iconique. Les chiles guajillo le piquant doux. L''ananas EN BOÎTE (pas frais, trop d''enzymes) apporte la douceur.',
 '[{"name":"Pâte d''achiote","qty":"50g"},{"name":"Chiles guajillo séchés","qty":"4","note":"Réhydratés 20 min dans l''eau chaude"},{"name":"Jus d''ananas EN BOÎTE","qty":"120ml"},{"name":"Vinaigre de cidre","qty":"40ml"},{"name":"Ail","qty":"4 gousses"},{"name":"Cumin","qty":"5g"},{"name":"Origan mexicain","qty":"5g"},{"name":"Chipotle en adobo","qty":"1 piment + sauce"},{"name":"Sel","qty":"8g"},{"name":"Poivre noir","qty":"3g"}]',
 '["Réhydrater les chiles 20 min dans l''eau chaude.","Mixer tout au blender jusqu''à consistance lisse.","Mariner le porc 12-24h au frigo.","Griller ou rôtir avec des tranches d''ananas.","Servir en tacos avec oignon, cilantro et salsa verde."]',
 '~400ml', '30 min + 12-24h', '{pulled_pork,spare_ribs}', 'Mexico — fusion libano-mexicaine', 'moyen',
 '{al-pastor,mexicain,achiote,ananas,tacos}', 'published', 54),

('Marinade Bulgogi', 'marinade-bulgogi', 'marinade',
 'Soja, poire asiatique, sésame, gochujang. BBQ coréen au fumoir.',
 'La poire asiatique attendrit la viande grâce à ses enzymes. Le gochujang apporte un piquant fermenté unique. Fusion BBQ coréen-américain.',
 '[{"name":"Sauce soja","qty":"80ml"},{"name":"Poire asiatique râpée","qty":"1 poire"},{"name":"Cassonade","qty":"40g"},{"name":"Huile de sésame","qty":"30ml"},{"name":"Gochujang","qty":"20g"},{"name":"Ail émincé","qty":"5 gousses"},{"name":"Gingembre râpé","qty":"15g"},{"name":"Oignon râpé","qty":"½ oignon"},{"name":"Poivre noir","qty":"5g"},{"name":"Graines de sésame","qty":"10g"}]',
 '["Mixer poire, ail, gingembre et oignon.","Ajouter soja, cassonade, sésame, gochujang.","Mariner 2-4h (tranches fines) ou 8-12h (pièce entière)."]',
 '~350ml', '10 min + 2-12h', '{brisket,beef_short_ribs,chuck_roast}', 'Corée — adapté BBQ US', 'moyen',
 '{coréen,bulgogi,soja,gochujang,fusion}', 'published', 55),

('Marinade Brochettes Boeuf (Shish Kebab)', 'marinade-shish-kebab', 'marinade',
 'Huile d''olive, oignon râpé, paprika, cumin. La marinade turque pour des brochettes tendres.',
 'Le shish kebab turc authentique utilise l''oignon râpé comme attendrisseur naturel. Le jus d''oignon pénètre la viande et la rend incroyablement tendre.',
 '[{"name":"Huile d''olive","qty":"60ml"},{"name":"Oignon râpé (jus inclus)","qty":"1 gros oignon"},{"name":"Paprika","qty":"10g"},{"name":"Cumin moulu","qty":"8g"},{"name":"Poudre d''ail","qty":"8g"},{"name":"Sel","qty":"10g"},{"name":"Poivre noir","qty":"5g"},{"name":"Sumac","qty":"5g","note":"Optionnel"},{"name":"Flocons de piment Alep","qty":"5g","note":"Optionnel"}]',
 '["Râper l''oignon et récupérer tout le jus.","Mélanger avec huile et épices.","Couper le boeuf en cubes de 3-4cm.","Mariner 4-12h au frigo.","Enfiler en alternant viande et légumes.","Griller sur braise vive 3-4 min par face."]',
 '~250ml', '10 min + 4-12h', '{beef_short_ribs,chuck_roast}', 'Turquie', 'facile',
 '{turc,shish-kebab,brochettes,boeuf,oignon}', 'published', 56),

('Marinade Brochettes Poulet Tikka', 'marinade-poulet-tikka', 'marinade',
 'Yaourt, garam masala, curcuma, citron. La marinade indienne onctueuse pour des brochettes tendres.',
 'Le tikka signifie "morceau" en hindi. Le yaourt sert de base pour attendrir ET pour que les épices adhèrent. Le garam masala donne la chaleur aromatique.',
 '[{"name":"Yaourt nature épais","qty":"200g"},{"name":"Garam masala","qty":"10g"},{"name":"Curcuma","qty":"5g"},{"name":"Paprika","qty":"10g"},{"name":"Cumin moulu","qty":"8g"},{"name":"Coriandre moulue","qty":"5g"},{"name":"Jus de citron","qty":"30ml"},{"name":"Ail émincé","qty":"4 gousses"},{"name":"Gingembre râpé","qty":"15g"},{"name":"Sel","qty":"8g"},{"name":"Cayenne","qty":"3g"},{"name":"Huile végétale","qty":"15ml"}]',
 '["Mélanger yaourt, épices, ail, gingembre et citron.","Couper le poulet en gros cubes.","Mariner 4-8h au frigo (pas plus, le yaourt sur-attendrit).","Enfiler sur brochettes métalliques.","Griller à haute température, servir avec sauce menthe."]',
 '~350ml — 1kg de poulet', '10 min + 4-8h', '{whole_chicken}', 'Inde — Pendjab', 'facile',
 '{tikka,indien,yaourt,brochettes,poulet}', 'published', 57),

('Marinade Satay (Cacahuète)', 'marinade-satay', 'marinade',
 'Lait de coco, cacahuète, citronnelle, curcuma. La marinade thaï/malaise pour des brochettes addictives.',
 'Le satay est répandu dans toute l''Asie du Sud-Est. La marinade elle-même contient peu de cacahuète — c''est la SAUCE de trempage qui en est riche. La citronnelle et le curcuma colorent et parfument.',
 '[{"name":"Lait de coco","qty":"100ml"},{"name":"Sauce soja","qty":"30ml"},{"name":"Beurre de cacahuète","qty":"20g"},{"name":"Cassonade","qty":"20g"},{"name":"Curcuma","qty":"5g"},{"name":"Citronnelle émincée","qty":"2 tiges"},{"name":"Ail","qty":"3 gousses"},{"name":"Coriandre moulue","qty":"5g"},{"name":"Cumin","qty":"3g"},{"name":"Sel","qty":"5g"}]',
 '["Mixer tous les ingrédients.","Couper la viande en fines lamelles.","Mariner 2-4h.","Enfiler en zigzag sur brochettes de bambou.","Griller sur charbon vif 2-3 min par côté.","Servir avec sauce cacahuète à part."]',
 '~250ml', '10 min + 2-4h', '{whole_chicken,beef_short_ribs}', 'Thaïlande / Malaisie', 'moyen',
 '{satay,thaï,cacahuète,citronnelle,brochettes}', 'published', 58),

('Marinade Yakitori', 'marinade-yakitori', 'marinade',
 'Tare yakitori : soja, mirin, saké, sucre. La sauce caramélisée des izakayas.',
 'Le tare yakitori est une sauce concentrée qui s''utilise en marinade puis en glaçage pendant la cuisson. Au Japon, certains restaurants gardent leur tare depuis des décennies.',
 '[{"name":"Sauce soja","qty":"100ml"},{"name":"Mirin","qty":"100ml"},{"name":"Saké","qty":"60ml"},{"name":"Sucre","qty":"40g"},{"name":"Gingembre frais","qty":"1 tranche"}]',
 '["Combiner tous les ingrédients dans une casserole.","Porter à ébullition, réduire le feu.","Mijoter 20 min jusqu''à réduire d''un tiers.","Retirer le gingembre.","Mariner le poulet en morceaux 30 min-1h.","Griller en badigeonnant de tare toutes les minutes."]',
 '~250ml', '25 min + 30 min-1h', '{whole_chicken}', 'Japon — izakaya', 'facile',
 '{yakitori,japonais,tare,soja,brochettes}', 'published', 59),

('Marinade Bourbon & Cassonade', 'marinade-bourbon-cassonade', 'marinade',
 'Bourbon, cassonade, sauce soja, ail. Riche et complexe pour porc et boeuf.',
 'Le bourbon apporte vanille et caramel qui se marient avec la fumée. La sauce soja ajoute de l''umami.',
 '[{"name":"Bourbon","qty":"120ml"},{"name":"Cassonade foncée","qty":"80g"},{"name":"Sauce soja","qty":"60ml"},{"name":"Vinaigre de cidre","qty":"30ml"},{"name":"Huile de sésame","qty":"15ml"},{"name":"Ail émincé","qty":"4 gousses"},{"name":"Gingembre râpé","qty":"10g"},{"name":"Poivre noir","qty":"5g"},{"name":"Flocons de piment","qty":"3g"}]',
 '["Dissoudre la cassonade dans le bourbon tiédi.","Ajouter tous les ingrédients.","Mariner 4-12h en sac zip au frigo.","Sécher avant d''appliquer le rub."]',
 '~350ml', '10 min + 4-12h', '{pulled_pork,chuck_roast,beef_short_ribs,spare_ribs}', 'Sud des États-Unis', 'moyen',
 '{bourbon,cassonade,umami}', 'published', 60),

('Marinade Citron-Herbes Méditerranée', 'marinade-citron-herbes', 'marinade',
 'Citron, origan, romarin, huile d''olive. Fraîche et herbacée pour poulet et agneau.',
 'Pas tout le BBQ doit être texan. L''acidité du citron attendrit, l''huile d''olive protège de la sécheresse.',
 '[{"name":"Huile d''olive","qty":"100ml"},{"name":"Jus de citron frais","qty":"80ml"},{"name":"Zeste de citron","qty":"2 citrons"},{"name":"Ail émincé","qty":"6 gousses"},{"name":"Origan frais","qty":"15g"},{"name":"Romarin frais","qty":"3 brins"},{"name":"Thym frais","qty":"5 brins"},{"name":"Sel","qty":"15g"},{"name":"Poivre noir","qty":"5g"}]',
 '["Mélanger tous les ingrédients.","Mariner poulet 4-8h, agneau 6-12h.","Éponger l''excédent avant cuisson."]',
 '~300ml', '5 min + 4-12h', '{whole_chicken}', 'Méditerranée', 'facile',
 '{méditerranée,citron,herbes,poulet,frais}', 'published', 61),

('Marinade Jerk Jamaïcain', 'marinade-jerk-jamaicain', 'marinade',
 'Scotch bonnet, piment de la Jamaïque, thym frais. Explosive et parfumée.',
 'La vraie marinade jerk : équilibre entre le scotch bonnet, l''allspice, le thym et le citron vert. Traditionnellement fumée sur du bois de pimento.',
 '[{"name":"Oignons verts","qty":"6 tiges"},{"name":"Scotch bonnet","qty":"2"},{"name":"Sauce soja","qty":"60ml"},{"name":"Jus de citron vert","qty":"45ml"},{"name":"Piment de la Jamaïque","qty":"15g"},{"name":"Thym frais","qty":"10 brins"},{"name":"Ail","qty":"6 gousses"},{"name":"Gingembre frais","qty":"20g"},{"name":"Cassonade","qty":"30g"},{"name":"Cannelle","qty":"3g"},{"name":"Muscade","qty":"2g"},{"name":"Poivre noir","qty":"5g"},{"name":"Huile végétale","qty":"30ml"}]',
 '["Mixer tout au blender en pâte.","Entailler la viande pour pénétration.","Masser généreusement.","Mariner 6-24h au frigo.","Fumer au bois de cerisier ou pommier."]',
 '~300ml', '15 min + 6-24h', '{whole_chicken}', 'Jamaïque', 'moyen',
 '{jerk,jamaïque,scotch-bonnet,épicé}', 'published', 62),

('Marinade Mojo Cubain', 'marinade-mojo-cubain', 'marinade',
 'Jus d''orange amère, ail, cumin, origan. La base du porc rôti cubain.',
 'Le mojo criollo est LA marinade de Cuba. L''orange amère (naranja agria) est l''ingrédient clé. Si introuvable, mélanger jus d''orange et jus de citron vert 50/50.',
 '[{"name":"Jus d''orange amère","qty":"150ml","note":"Ou 75ml orange + 75ml citron vert"},{"name":"Huile d''olive","qty":"60ml"},{"name":"Ail émincé","qty":"8 gousses"},{"name":"Cumin moulu","qty":"10g"},{"name":"Origan séché","qty":"8g"},{"name":"Sel","qty":"10g"},{"name":"Poivre noir","qty":"5g"}]',
 '["Chauffer l''huile, ajouter l''ail — ne pas brunir.","Ajouter jus d''agrumes, cumin, origan, sel, poivre.","Laisser refroidir.","Injecter ET mariner le porc 12-24h.","Rôtir ou fumer lentement."]',
 '~300ml', '10 min + 12-24h', '{pulled_pork,spare_ribs}', 'Cuba', 'facile',
 '{cubain,mojo,orange,ail,porc}', 'published', 63),

('Marinade Harissa', 'marinade-harissa', 'marinade',
 'Pâte de harissa, huile d''olive, citron, cumin. Piquant et fumé à la tunisienne.',
 'La harissa est une pâte de piments rouges nord-africaine. Combinée avec huile d''olive et citron, elle fait une marinade rapide et puissante pour les brochettes.',
 '[{"name":"Pâte de harissa","qty":"60g"},{"name":"Huile d''olive","qty":"60ml"},{"name":"Jus de citron","qty":"30ml"},{"name":"Cumin moulu","qty":"5g"},{"name":"Coriandre moulue","qty":"5g"},{"name":"Ail émincé","qty":"3 gousses"},{"name":"Sel","qty":"5g"},{"name":"Miel","qty":"15ml","note":"Pour adoucir le piquant"}]',
 '["Mélanger harissa, huile, citron et épices.","Masser la viande.","Mariner 2-4h (pas plus, la harissa est puissante).","Griller en brochettes ou pièce entière.","Servir avec couscous et yaourt."]',
 '~200ml', '5 min + 2-4h', '{whole_chicken,beef_short_ribs,chuck_roast}', 'Tunisie / Afrique du Nord', 'facile',
 '{harissa,tunisien,piquant,brochettes}', 'published', 64),

('Marinade Peri Peri', 'marinade-peri-peri', 'marinade',
 'Piments bird''s eye, ail, paprika, citron, huile. Le classique portugais-africain.',
 'La marinade peri peri (piri piri) est née de la rencontre entre les colons portugais et les piments africains. Ça donne un poulet grillé épicé, juteux et acidulé.',
 '[{"name":"Piments bird''s eye rouges","qty":"6-8","note":"Ou 4 pour moins de feu"},{"name":"Ail","qty":"6 gousses"},{"name":"Paprika fumé","qty":"10g"},{"name":"Jus de citron","qty":"60ml"},{"name":"Vinaigre de vin rouge","qty":"30ml"},{"name":"Huile d''olive","qty":"60ml"},{"name":"Origan séché","qty":"5g"},{"name":"Sel","qty":"8g"},{"name":"Sucre","qty":"10g"}]',
 '["Mixer piments, ail, paprika et citron.","Ajouter vinaigre, huile, origan, sel, sucre.","Mariner le poulet 4-12h au frigo.","Griller en le badigeonnant souvent."]',
 '~250ml', '10 min + 4-12h', '{whole_chicken}', 'Portugal / Mozambique', 'moyen',
 '{peri-peri,portugais,piquant,poulet}', 'published', 65),

-- ═══════════════════════════════════════════════════════════
-- MOPS (3)
-- ═══════════════════════════════════════════════════════════

('Texas Mop Sauce', 'texas-mop-sauce', 'mop',
 'Vinaigre, bière, épices et jus de cuisson. Le mop texan pour garder le brisket juteux.',
 'Appliqué au pinceau toutes les 45-60 min. Maintient l''humidité de surface pour une bark uniforme. La bière apporte des sucres pour la caramélisation.',
 '[{"name":"Vinaigre de cidre","qty":"250ml"},{"name":"Bière lager","qty":"250ml"},{"name":"Eau","qty":"125ml"},{"name":"Poudre d''oignon","qty":"15g"},{"name":"Poudre d''ail","qty":"10g"},{"name":"Chili powder","qty":"10g"},{"name":"Sel","qty":"8g"},{"name":"Poivre noir","qty":"5g"},{"name":"Sauce piquante","qty":"5ml"}]',
 '["Porter à ébullition.","Mijoter 15 min, laisser refroidir.","Appliquer toutes les 45-60 min.","Arrêter quand on wrappe."]',
 '~600ml', '20 min', '{brisket,beef_short_ribs,chuck_roast}', 'Central Texas', 'facile',
 '{texas,mop,brisket,vinaigre}', 'published', 70),

('Carolina Vinegar Mop', 'carolina-vinegar-mop', 'mop',
 'Ultra vinaigré et piquant. Le mop de la Caroline pour le porc fumé.',
 'Pas de tomate, pas de sucre (ou presque). Le vinaigre coupe le gras du pulled pork. Sert aussi de sauce de table.',
 '[{"name":"Vinaigre de cidre","qty":"500ml"},{"name":"Flocons de piment rouge","qty":"15g"},{"name":"Poivre noir concassé","qty":"10g"},{"name":"Sel","qty":"10g"},{"name":"Sucre","qty":"10g"},{"name":"Sauce piquante","qty":"15ml"}]',
 '["Mélanger dans un bocal, secouer.","Infuser 2h minimum.","Appliquer toutes les 30-45 min.","Servir aussi en sauce de table sur le pulled pork."]',
 '~550ml', '5 min + 2h', '{pulled_pork,spare_ribs}', 'Eastern North Carolina', 'facile',
 '{carolina,vinaigre,porc}', 'published', 71),

('Mop Beurre-Épices', 'mop-beurre-epices', 'mop',
 'Beurre, jus de pomme, rub et miel. Un mop riche pour une bark dorée et laquée.',
 'Le gras du beurre aide à la bark, les épices renforcent les saveurs, le jus de pomme adoucit.',
 '[{"name":"Beurre fondu","qty":"120g"},{"name":"Jus de pomme","qty":"250ml"},{"name":"Votre rub favori","qty":"20g"},{"name":"Miel","qty":"30ml"},{"name":"Vinaigre de cidre","qty":"30ml"},{"name":"Sauce Worcestershire","qty":"15ml"}]',
 '["Fondre le beurre, ajouter le reste.","Garder tiède pendant la cuisson.","Appliquer toutes les 30-45 min."]',
 '~450ml', '5 min', '{spare_ribs,baby_back_ribs,whole_chicken}', 'Style compétition KCBS', 'facile',
 '{beurre,ribs,laqué,mop}', 'published', 72),

-- ═══════════════════════════════════════════════════════════
-- INJECTIONS (2)
-- ═══════════════════════════════════════════════════════════

('Injection Compétition Brisket', 'injection-competition-brisket', 'injection',
 'Bouillon de boeuf, beurre et umami. L''injection qui fait la différence en compétition.',
 'L''injection apporte humidité et goût au coeur de la viande. La Parkay (margarine liquide) est le secret des compétiteurs américains.',
 '[{"name":"Bouillon de boeuf concentré","qty":"250ml"},{"name":"Margarine liquide ou beurre fondu","qty":"60ml"},{"name":"Sauce Worcestershire","qty":"30ml"},{"name":"Poudre d''oignon","qty":"10g"},{"name":"Poudre d''ail","qty":"5g"},{"name":"MSG","qty":"5g","note":"Optionnel"},{"name":"Sel","qty":"5g"}]',
 '["Chauffer bouillon + margarine (ne pas bouillir).","Ajouter épices, dissoudre.","Filtrer à la passoire fine.","Injecter en grille de 5cm.","Repos 4h minimum au frigo."]',
 '~350ml', '10 min + 4h', '{brisket}', 'Circuit compétition KCBS/FBA', 'avancé',
 '{injection,compétition,brisket,umami}', 'published', 80),

('Injection Porc Jus de Pomme', 'injection-porc-jus-pomme', 'injection',
 'Jus de pomme, beurre, sel. L''injection classique pour un pulled pork ultra juteux.',
 'La douceur de la pomme se marie naturellement avec le porc. Injecter surtout dans les zones maigres.',
 '[{"name":"Jus de pomme (sans pulpe)","qty":"250ml"},{"name":"Beurre fondu","qty":"60ml"},{"name":"Sucre","qty":"20g"},{"name":"Sel","qty":"15g"},{"name":"Sauce Worcestershire","qty":"15ml"},{"name":"Poudre d''ail","qty":"5g"}]',
 '["Chauffer jus de pomme + beurre à feu doux.","Dissoudre sucre et sel.","Filtrer et tiédir.","Injecter en grille de 5cm.","Repos 4-8h au frigo."]',
 '~350ml', '10 min + 4-8h', '{pulled_pork}', 'Tradition compétition US', 'moyen',
 '{injection,porc,pomme,juteux}', 'published', 81),

-- ═══════════════════════════════════════════════════════════
-- GLAZES (2)
-- ═══════════════════════════════════════════════════════════

('Glaze Miel-Chipotle', 'glaze-miel-chipotle', 'glaze',
 'Miel, chipotle en adobo, vinaigre. Glaçage fumé-sucré-piquant pour les 30 dernières minutes.',
 'Le miel apporte sucre et brillance, le chipotle le piquant fumé. Attention : le miel brûle au-dessus de 180°C.',
 '[{"name":"Miel","qty":"120ml"},{"name":"Chipotle en adobo (mixé)","qty":"30g"},{"name":"Vinaigre de cidre","qty":"30ml"},{"name":"Sauce soja","qty":"15ml"},{"name":"Beurre","qty":"30g"},{"name":"Poudre d''ail","qty":"5g"}]',
 '["Fondre le beurre, ajouter le miel.","Incorporer chipotle, vinaigre, soja, ail.","Mijoter 5 min.","Appliquer 30-45 min avant la fin.","2 couches espacées de 15 min."]',
 '~250ml', '10 min', '{spare_ribs,baby_back_ribs,whole_chicken}', 'Sud des États-Unis', 'facile',
 '{glaze,miel,chipotle,laqué}', 'published', 90),

('Glaze Érable-Moutarde', 'glaze-erable-moutarde', 'glaze',
 'Sirop d''érable, moutarde de Dijon, bourbon. Doux, piquant et élégant.',
 'L''érable caramélise magnifiquement. La moutarde coupe le sucre. Le bourbon lie le tout.',
 '[{"name":"Sirop d''érable pur","qty":"120ml"},{"name":"Moutarde de Dijon","qty":"60ml"},{"name":"Bourbon","qty":"30ml"},{"name":"Vinaigre de cidre","qty":"15ml"},{"name":"Sel","qty":"3g"},{"name":"Poivre noir","qty":"2g"}]',
 '["Mélanger dans une casserole.","Chauffer 3-4 min à feu doux (ne pas bouillir).","Appliquer 20-30 min avant la fin."]',
 '~250ml', '5 min', '{baby_back_ribs,whole_chicken,spare_ribs}', 'Nouvelle-Angleterre / Québec', 'facile',
 '{glaze,érable,moutarde,bourbon}', 'published', 91)

ON CONFLICT (slug) DO NOTHING;
