-- ══════════════════════════════════════════════════════════════
-- 016 — Seed essences de bois de fumage
-- Sources vérifiées : AmazingRibs.com (Meathead Goldwyn),
-- Texas A&M Forest Service, Traeger, Smokinlicious, MasterClass
-- ══════════════════════════════════════════════════════════════

DELETE FROM woods;

INSERT INTO woods (id, name, scientific_name, emoji, intensity, flavor_profile, description, best_meats, avoid_meats, burn_characteristics, origin, availability_eu, safety_notes, pitmaster_tips, source, sort_order) VALUES

-- ═══════════════════════════════════════════════════════════
-- INTENSITÉ FORTE
-- ═══════════════════════════════════════════════════════════

('hickory', 'Hickory', 'Carya ovata', '🌰', 'fort',
 'Puissant, sucré, arôme de bacon fumé',
 'Le bois le plus emblématique du BBQ américain. Son goût intense et sucré rappelle le bacon fumé. C''est LE bois du pulled pork et des ribs en compétition. Très populaire dans le Sud des États-Unis, il produit une fumée épaisse et aromatique qui imprègne profondément la viande. À utiliser avec modération sur les longues cuissons pour éviter l''amertume.',
 '{pulled_pork,spare_ribs,baby_back_ribs,whole_chicken,brisket}',
 '{}',
 'Brûle chaud et régulier. L''un des bois durs domestiques les plus denses. Excellent lit de braises. Bonne capacité de combustion longue.',
 'Est des États-Unis',
 'moyenne',
 'Bois dur sûr. Aucun risque connu. Peut devenir amer si sur-fumé (>6h de fumée dense).',
 'Excellent pour le porc en compétition. Les juges adorent le hickory sur les ribs. Se marie bien avec le cerisier pour un profil équilibré sucré-fumé.',
 'Texas A&M Forest Service, AmazingRibs.com, Traeger', 1),

('mesquite', 'Mesquite', 'Prosopis glandulosa', '🏜️', 'fort',
 'Intense, épicé, terreux, poivré',
 'Le roi du Texas BBQ. Le mesquite possède le taux de lignine le plus élevé (64%) de tous les bois de fumage, ce qui lui confère une intensité incomparable. Son goût épicé et terreux est parfait pour le boeuf, mais il peut facilement dominer les viandes plus délicates. C''est le bois des briskets de compétition texans.',
 '{brisket,beef_short_ribs,tomahawk,prime_rib}',
 '{whole_chicken,baby_back_ribs}',
 'Brûle très chaud. Produit un volume important de fumée. BTU élevé. Bois dense créant un excellent lit de braises.',
 'Sud-Ouest des États-Unis, Mexique',
 'limitee',
 'Bois dur sûr. Attention : sa puissance peut rendre la viande amère si la fumée est trop dense ou trop longue. Préférer les morceaux (chunks) aux copeaux.',
 'L''étalon-or pour le brisket texan. Ne jamais utiliser seul sur du porc ou de la volaille — trop puissant. Idéal en mélange avec du chêne (70% chêne / 30% mesquite).',
 'Texas A&M Forest Service, MasterClass', 2),

('noyer', 'Noyer', 'Juglans regia', '🥜', 'fort',
 'Très intense, légèrement amer, fumée lourde',
 'Le noyer produit une fumée très dense et intense, presque amère si utilisé seul. C''est un bois de spécialiste, à réserver aux viandes fortes (gibier, boeuf). Le noyer noir (Juglans nigra) est encore plus puissant que le noyer commun européen. Toujours le mélanger avec un bois plus doux.',
 '{brisket,chuck_roast,beef_short_ribs}',
 '{whole_chicken,baby_back_ribs}',
 'Dense, brûle chaud et longtemps. Produit une fumée épaisse.',
 'Europe (noyer commun), Amérique du Nord (noyer noir)',
 'bonne',
 'Bois dur sûr mais à utiliser avec parcimonie. Ne jamais utiliser seul — toujours mélanger avec pommier, poirier ou cerisier.',
 'Mélange classique : 20% noyer + 80% pommier. Le noyer apporte la profondeur, le fruitier apporte la douceur.',
 'The MeatStick, AmazingRibs.com', 3),

-- ═══════════════════════════════════════════════════════════
-- INTENSITÉ MOYENNE
-- ═══════════════════════════════════════════════════════════

('chene', 'Chêne', 'Quercus robur / Q. alba', '🌳', 'moyen',
 'Terreux, léger, équilibré, propre',
 'Le bois le plus polyvalent du BBQ. Le chêne est le choix n°1 des pitmasters professionnels pour sa régularité et son profil équilibré. Il ajoute une couche de fumée sans jamais dominer la viande. Le chêne blanc américain (Q. alba) est légèrement plus doux que le chêne rouge (Q. rubra). Le Post Oak est le standard du BBQ texan, utilisé par Aaron Franklin.',
 '{brisket,pulled_pork,spare_ribs,baby_back_ribs,beef_short_ribs,whole_chicken,tomahawk,prime_rib,chuck_roast}',
 '{}',
 'Dense, combustion régulière. Excellent lit de braises. Longue durée (6-8h par bûche). Température stable. Le meilleur bois pour maintenir un feu constant.',
 'Europe (chêne sessile, pédonculé), Amérique du Nord (blanc, rouge, Post Oak)',
 'excellente',
 'Bois dur parfaitement sûr. Séchage critique : humidité <20%. Le chêne européen est tout aussi bon que l''américain pour le fumage.',
 'Le bois le plus populaire en compétition. Les juges le préfèrent pour sa régularité. Aaron Franklin utilise exclusivement du Post Oak. Se marie avec tout. Si tu ne sais pas quel bois choisir, prends du chêne.',
 'Texas A&M, AmazingRibs.com, Texas Monthly', 4),

('pecan', 'Pécan', 'Carya illinoinensis', '🥧', 'moyen',
 'Doux, sucré, noisette, version douce du hickory',
 'Le pécan est le cousin plus doux du hickory. Il offre un goût noisette subtil sans l''intensité parfois agressive du hickory. C''est un excellent bois polyvalent, particulièrement apprécié pour la volaille. Il ajoute une teinte rougeâtre à la viande. Brûle très lentement, idéal pour le low & slow.',
 '{whole_chicken,brisket,pulled_pork,spare_ribs,baby_back_ribs,beef_short_ribs}',
 '{}',
 'Brûle très lentement. Excellent pour les longues sessions low & slow. Chaleur régulière et contrôlée. Peut devenir âpre si surdosé.',
 'Texas, Sud des États-Unis',
 'moyenne',
 'Bois dur sûr. Issu d''un arbre produisant des noix comestibles (indicateur de qualité). Modérer la quantité sur les cuissons >8h.',
 'Le bois préféré de nombreux pitmasters pour la volaille en compétition. Excellent en mélange avec du chêne pour le brisket.',
 'Texas A&M, Wisconsin Firewood Guide, MasterClass', 5),

('hetre', 'Hêtre', 'Fagus sylvatica', '🌿', 'moyen',
 'Doux, légèrement sucré, équilibré, propre',
 'Le bois de référence en Europe. Le hêtre est utilisé depuis des siècles pour le fumage des saucisses allemandes et du saumon scandinave. Son profil doux et propre en fait un excellent polyvalent. Il brûle proprement avec peu de cendres. C''est l''équivalent européen du chêne américain pour le BBQ.',
 '{pulled_pork,spare_ribs,baby_back_ribs,whole_chicken,brisket,beef_short_ribs}',
 '{}',
 'Brûle proprement avec peu de cendres. Bois dur dense, brûle plus longtemps et plus chaud que beaucoup de bois. Nécessite un bon séchage (humidité 20-25% max).',
 'Europe (Allemagne, Scandinavie, France)',
 'excellente',
 'Bois dur parfaitement sûr. Le bois de fumage le plus accessible en Europe. Nécessite un séchage correct pour éviter l''amertume.',
 'Le bois traditionnel des saucisses allemandes, réputées mondialement. Assez léger pour ne jamais surdoser. Excellent point de départ pour les débutants européens.',
 'Smokinlicious, BBQ Flavour', 6),

('olivier', 'Olivier', 'Olea europaea', '🫒', 'moyen',
 'Similaire au mesquite mais plus léger, savoureux, méditerranéen',
 'L''olivier est le bois de fumage méditerranéen par excellence. Son profil rappelle le mesquite mais en nettement moins agressif. Il apporte une saveur unique, savoureuse et légèrement terreuse. Très dense, il brûle longtemps et produit une chaleur intense. Excellent pour l''agneau et la volaille.',
 '{whole_chicken,pulled_pork,spare_ribs}',
 '{}',
 'Bois très dense. Brûle chaud et longtemps. Bonne production de braises.',
 'Bassin méditerranéen (Espagne, Grèce, Italie, Sud de la France)',
 'excellente',
 'Bois dur sûr. Combustible traditionnel méditerranéen. Souvent disponible à partir de tailles d''oliviers.',
 'Excellent pour donner une touche méditerranéenne au BBQ. Se marie parfaitement avec de l''agneau et des herbes de Provence. Souvent gratuit ou peu cher près des oliveraies.',
 'BBQ Brethren Forums', 7),

('vigne', 'Sarments de Vigne', 'Vitis vinifera', '🍇', 'moyen',
 'Intensité moyenne, unique, fruité-terreux',
 'Les sarments de vigne sont une tradition de la cuisine au feu méditerranéenne. Ils brûlent vite et chaud, produisant une fumée parfumée et fruitée. Utilisés en Espagne, dans le Sud de la France et en Italie pour griller viandes et poissons. Un choix original et local pour les pitmasters européens.',
 '{whole_chicken,spare_ribs,pulled_pork}',
 '{}',
 'Brûle vite et chaud. Crée de bonnes braises. Durée de combustion plus courte que les bois massifs.',
 'Bassin méditerranéen, toute la France viticole',
 'excellente',
 'Sûr si non traité. S''assurer que les sarments ne proviennent pas de vignes traitées chimiquement. Privilégier les vignes bio.',
 'Souvent gratuit si tu connais un vigneron ! Les sarments se récupèrent après la taille d''hiver. Brûlent vite : les utiliser en complément d''un bois principal.',
 'Traditions culinaires espagnoles et françaises', 8),

('erable', 'Érable', 'Acer saccharum', '🍁', 'moyen',
 'Doux, sucre caramélisé, chaleureux, propre',
 'L''érable (surtout l''érable à sucre) produit une fumée douce aux notes de sucre caramélisé — logique pour l''arbre du sirop d''érable. Son profil est savoureux sans être sucré-dessert. Il brûle proprement et produit une fumée bleue de qualité. Excellent pour la volaille et le poisson.',
 '{whole_chicken,pulled_pork,spare_ribs,baby_back_ribs}',
 '{}',
 'Brûle proprement avec une chaleur régulière. Bois séché brûle chaud et constant. Braises durables. Excellent pour les longues cuissons sans amertume.',
 'Amérique du Nord, Europe (érable champêtre, sycomore)',
 'bonne',
 'Bois dur sûr. Doit être correctement séché (humidité <20%) pour éviter l''amertume. L''érable champêtre européen fonctionne aussi.',
 'Souvent mélangé avec du chêne, hickory ou cerisier pour un profil équilibré. Les juges apprécient les mélanges à base d''érable.',
 'Destination BBQ', 9),

('whiskey-barrel', 'Bois de Fût de Whiskey', 'Quercus alba (fût)', '🥃', 'moyen',
 'Vanille, caramel, cassonade, notes de bourbon',
 'Le bois de fûts de bourbon recyclés (chêne blanc américain vieilli 4+ ans) apporte des saveurs uniques de vanille, caramel et cassonade issues du vieillissement du whiskey. C''est un produit premium qui donne un caractère incomparable à la viande. Les fûts sont séchés au four, ce qui garantit une combustion propre et uniforme.',
 '{brisket,beef_short_ribs,pulled_pork,spare_ribs,tomahawk}',
 '{}',
 'Brûle lentement, longtemps et chaud. Chaleur constante. Excellent lit de braises. Les blocs séchés au four offrent une combustion uniforme et propre.',
 'Kentucky, Tennessee (fûts de bourbon américains)',
 'limitee',
 'Sûr uniquement si les fûts ont servi au vieillissement de spiritueux alimentaires. Ne JAMAIS utiliser de fûts industriels ou chimiques.',
 'Produit premium pour les grandes occasions. Disponible en ligne chez des fournisseurs spécialisés. Donne un caractère unique que les invités remarquent immédiatement.',
 'Midwest Barrel Co', 10),

-- ═══════════════════════════════════════════════════════════
-- INTENSITÉ LÉGÈRE
-- ═══════════════════════════════════════════════════════════

('cerisier', 'Cerisier', 'Prunus avium', '🍒', 'leger',
 'Doux, fruité, sucré avec une subtilité fumée',
 'Le cerisier est l''un des bois les plus appréciés en compétition BBQ. Sa fumée douce et fruitée ajoute une belle couleur rouge foncé à la viande. Moins intense que le hickory, il est parfait pour les ribs et le porc. Souvent mélangé avec du hickory pour un profil « meilleur des deux mondes ». Un favori des juges.',
 '{spare_ribs,baby_back_ribs,pulled_pork,whole_chicken}',
 '{}',
 'Brûle plus lentement que les copeaux mais pas aussi longtemps que les chunks de hickory. Température modérée. Bon pour 30-45 minutes de fumage.',
 'Amérique du Nord, Europe',
 'bonne',
 'Bois dur parfaitement sûr. L''un des bois les plus appréciés des juges en compétition.',
 'Le mélange cerisier + hickory est un classique de compétition pour les ribs. Le cerisier donne une couleur acajou magnifique à la viande. Les juges mangent d''abord avec les yeux.',
 'AmazingRibs.com, Traeger', 11),

('pommier', 'Pommier', 'Malus domestica', '🍎', 'leger',
 'Sucré, doux, subtil, fruité',
 'Le pommier est le bois fruitier le plus fiable et le plus prévisible. Sa fumée douce et sucrée convient à pratiquement toutes les viandes sans jamais les dominer. C''est le choix idéal pour les débutants et un incontournable des mélanges de compétition. Très accessible en Europe grâce aux vergers.',
 '{spare_ribs,baby_back_ribs,whole_chicken,pulled_pork}',
 '{}',
 'Similaire au cerisier. Combustion modérée et régulière. Chaleur constante. Bon pour un fumage contrôlé.',
 'Asie centrale (origine), cultivé mondialement',
 'excellente',
 'Bois dur parfaitement sûr. L''un des plus fiables pour les débutants. Résultats prévisibles et constants.',
 'Si tu débutes le fumage, commence par le pommier. Impossible de se tromper. Demande à un arboriculteur local — ils donnent souvent le bois de taille.',
 'AmazingRibs.com, Destination BBQ', 12),

('aulne', 'Aulne', 'Alnus rubra', '🌊', 'leger',
 'Très délicat, légèrement sucré, subtil',
 'L''aulne est le bois traditionnel du fumage du saumon dans le Pacifique Nord-Ouest. Sa fumée est l''une des plus douces et délicates, parfaite pour les poissons et fruits de mer. Il ajoute une touche de fumée sans jamais masquer le goût naturel de la protéine.',
 '{whole_chicken}',
 '{}',
 'Brûle rapidement mais régulièrement. Plus léger que les bois durs. Bon pour les sessions de fumage courtes.',
 'Amérique du Nord (Pacifique Nord-Ouest), Europe (aulne glutineux)',
 'bonne',
 'Bois sûr. Choix traditionnel du fumage du saumon.',
 'Le bois de référence pour le poisson fumé. L''aulne glutineux européen (Alnus glutinosa) est un excellent substitut local.',
 'Traditions du Pacifique Nord-Ouest', 13),

('pecher', 'Pêcher', 'Prunus persica', '🍑', 'leger',
 'Sucré, doux, fruité, boisé',
 'Le pêcher offre une fumée douce et fruitée, légèrement plus sucrée que le cerisier. C''est un excellent choix pour les viandes blanches et le porc. Très accessible en Europe grâce aux vergers méditerranéens. Son profil délicat en fait un bon choix pour le fumage à froid également.',
 '{whole_chicken,pulled_pork,spare_ribs}',
 '{}',
 'Similaire au cerisier. Combustion modérée et régulière.',
 'Chine (origine), cultivé en Europe méditerranéenne',
 'excellente',
 'Bois dur sûr issu d''un arbre fruitier.',
 'Souvent disponible gratuitement près des vergers lors des tailles. Excellent sur la volaille et le porc.',
 'BBQ Brethren, Smoking Meat Forums', 14),

('poirier', 'Poirier', 'Pyrus communis', '🍐', 'leger',
 'Subtil, délicat, légèrement fruité',
 'Le poirier est un bois fruitier européen natif, disponible partout. Sa fumée est parmi les plus délicates — parfaite pour les viandes qui n''ont pas besoin de beaucoup de fumée. C''est le bois fruitier le plus doux, encore plus subtil que le pommier.',
 '{whole_chicken,pulled_pork}',
 '{}',
 'Similaire aux autres bois fruitiers. Combustion modérée.',
 'Europe (natif), cultivé mondialement',
 'excellente',
 'Bois dur sûr. Bois fruitier européen préféré. Très faible coût.',
 'Le bois fruitier le plus facile à trouver en Europe. Demande chez les pépiniéristes ou récupère du bois de taille. Parfait pour les débutants qui veulent juste une touche de fumée.',
 'Guides de fumage européens', 15),

-- ═══════════════════════════════════════════════════════════
-- BOIS TOXIQUES / INTERDITS
-- ═══════════════════════════════════════════════════════════

('pin', 'Pin', 'Pinus spp.', '🚫', 'fort',
 'TOXIQUE — Ne jamais utiliser',
 'Le pin et tous les résineux (épicéa, sapin) contiennent des taux élevés de résine et de terpènes. Leur combustion produit une fumée âcre, des substances toxiques et un goût imbuvable. La résine encrasse le fumoir et peut provoquer des flambées dangereuses.',
 '{}', '{}',
 'Brûle extrêmement vite. Flammes hautes et incontrôlables. Résine explosive.',
 'Mondial', 'excellente',
 'INTERDIT pour le fumage alimentaire. Résine et terpènes toxiques à la combustion. Risque d''incendie élevé.',
 'Si quelqu''un te propose du pin pour fumer — fuis. Ça vaut pour TOUS les résineux : pin, sapin, épicéa, cèdre.',
 'Food Fire Friends, Rackz BBQ', 90),

('cedre', 'Cèdre', 'Cedrus spp.', '🚫', 'fort',
 'TOXIQUE — Ne jamais utiliser pour fumer',
 'Le cèdre contient des huiles aromatiques dont la combustion provoque des irritations cutanées (dermatite), rhinite, conjonctivite et « asthme du cèdre ». Les planches de cèdre pour la cuisson au four sont différentes — elles ne brûlent pas, elles fument à basse température. Ne JAMAIS brûler du cèdre dans un fumoir.',
 '{}', '{}',
 'Haute teneur en huile. Combustion de résine irritante.',
 'Mondial', 'bonne',
 'DANGEREUX : dermatite, rhinite, conjonctivite, asthme du cèdre documentés. Ne pas confondre avec les planches de cèdre pour cuisson au four (usage différent).',
 'La planche de cèdre au four/grill = OK (elle ne brûle pas vraiment). Le cèdre dans un fumoir = DANGER.',
 'Wildwood Grilling', 91),

('bois-traite', 'Bois traité / peint', NULL, '☠️', 'fort',
 'EXTRÊMEMENT TOXIQUE — Ne jamais utiliser',
 'Le bois traité (CCA, autoclave), peint, verni ou issu de palettes industrielles contient des produits chimiques dangereux : arsenic, chrome, cuivre, formaldéhyde. Leur combustion libère des fumées hautement toxiques qui contaminent la nourriture. Risque grave pour la santé.',
 '{}', '{}',
 'Combustion de produits chimiques toxiques.',
 'N/A', NULL,
 'EXTRÊMEMENT DANGEREUX. Arsenic, chrome et autres composés cancérigènes. Ne JAMAIS utiliser de bois de chantier, palettes, meubles ou bois récupéré dont on ne connaît pas l''origine.',
 'Règle d''or : si tu ne connais pas l''origine exacte du bois, ne l''utilise pas. Uniquement du bois non traité dont tu connais la provenance.',
 'Rackz BBQ, Tasting Table, Chowhound', 92),

('moisi', 'Bois moisi', NULL, '🦠', 'fort',
 'TOXIQUE — Ne jamais utiliser',
 'Le bois moisi ou couvert de moisissures contient des mycotoxines — des toxines fongiques dangereuses pour la santé. La combustion ne détruit pas toutes les mycotoxines et peut les disperser dans la fumée. Risque de maladie alimentaire grave.',
 '{}', '{}',
 'Combustion de mycotoxines.',
 'N/A', NULL,
 'DANGEREUX : mycotoxines, toxines fongiques, risque de maladie alimentaire. Inspecter visuellement tout bois avant usage. Si moisissure visible → poubelle.',
 'Toujours stocker le bois au sec, surélevé, avec une bonne circulation d''air. Inspecter chaque morceau avant de l''utiliser.',
 'Chowhound', 93);
