-- 026_seed_cooking_profiles.sql
-- Seed les profils de cuisson depuis data.js dans la table cooking_profiles
-- Permet l'édition admin des timelines du calculateur

INSERT INTO cooking_profiles (id, name, category, icon, cook_type, supports_wrap, temp_bands, fixed_times, wrap_reduction_percent, rest_min, rest_max, reverse_sear, doneness_targets, cues, sort_order, is_active)
VALUES
  -- ── BOEUF ──
  (
    'brisket',
    'Brisket',
    'boeuf',
    '🥩',
    'low_and_slow',
    true,
    '[{"temp_c":107,"min_per_kg":175},{"temp_c":121,"min_per_kg":135},{"temp_c":135,"min_per_kg":90}]'::jsonb,
    null,
    15,
    60,
    120,
    null,
    null,
    '{"stall_temp_min":65,"stall_temp_max":77,"wrap_temp_min":68,"wrap_temp_max":74,"begin_test_temp":90,"target_temp_min":93,"target_temp_max":98,"visual_wrap":"La bark est sombre, sèche au toucher, presque noire. Elle ne se raye plus à l''ongle. Le gras de surface a rendu et s''est figé en une croûte ferme. Si tu hésites, attends encore 15 min — mieux vaut wrapper trop tard que trop tôt.","probe_tender":"La sonde thermique entre comme dans du beurre mou, sans aucune résistance. Teste au point le plus épais du flat. Si ça accroche encore, remets 30 min et reteste."}'::jsonb,
    1,
    true
  ),
  (
    'beef_short_ribs',
    'Beef Short Ribs',
    'boeuf',
    '🥩',
    'low_and_slow',
    true,
    '[{"temp_c":107,"min_per_kg":240},{"temp_c":121,"min_per_kg":185},{"temp_c":135,"min_per_kg":135}]'::jsonb,
    null,
    10,
    30,
    60,
    null,
    null,
    '{"stall_temp_min":65,"stall_temp_max":77,"wrap_temp_min":68,"wrap_temp_max":74,"begin_test_temp":92,"target_temp_min":93,"target_temp_max":99,"visual_wrap":"L''extérieur est bien caramélisé, la bark a viré au brun-noir profond. La viande a rétréci et les os dépassent nettement. C''est le moment.","probe_tender":"La sonde entre entre les fibres avec une résistance minimale. La viande tremble comme de la gelée quand tu secoues légèrement le rack."}'::jsonb,
    2,
    true
  ),
  (
    'chuck_roast',
    'Paleron / Chuck Roast',
    'boeuf',
    '🥩',
    'low_and_slow',
    true,
    '[{"temp_c":107,"min_per_kg":140},{"temp_c":121,"min_per_kg":110},{"temp_c":135,"min_per_kg":85}]'::jsonb,
    null,
    12,
    30,
    60,
    null,
    null,
    '{"stall_temp_min":65,"stall_temp_max":77,"wrap_temp_min":71,"wrap_temp_max":77,"begin_test_temp":91,"target_temp_min":91,"target_temp_max":96,"visual_wrap":"La bark est bien formée, couleur acajou à brun foncé. Le morceau a visiblement réduit de volume. Le gras de surface a rendu.","probe_tender":"La sonde entre sans résistance franche. La viande se défait facilement en tirant avec deux fourchettes — c''est prêt pour du pulled beef."}'::jsonb,
    3,
    true
  ),
  (
    'prime_rib',
    'Côte de bœuf',
    'boeuf',
    '🥩',
    'reverse_sear',
    false,
    '[{"temp_c":107,"min_per_kg":30},{"temp_c":121,"min_per_kg":22},{"temp_c":135,"min_per_kg":16}]'::jsonb,
    null,
    0,
    10,
    20,
    '{"pull_before_target_c":8,"sear_total_minutes_min":3,"sear_total_minutes_max":6}'::jsonb,
    '{"bleu":45,"rare":52,"medium_rare":54,"medium":60}'::jsonb,
    '{"reverse_note":"Place la côte en zone indirecte à 110°C avec des copeaux de bois. Ferme le couvercle et surveille la sonde. Sors la viande 8°C sous ta cible. Saisie violente 1-2 min par face à 250°C+. Repos 10 min sous alu lâche."}'::jsonb,
    4,
    true
  ),
  (
    'tomahawk',
    'Tomahawk / steak épais',
    'boeuf',
    '🥩',
    'reverse_sear',
    false,
    '[{"temp_c":107,"min_per_kg":55},{"temp_c":121,"min_per_kg":40},{"temp_c":135,"min_per_kg":30}]'::jsonb,
    null,
    0,
    5,
    10,
    '{"pull_before_target_c":6,"sear_total_minutes_min":3,"sear_total_minutes_max":6}'::jsonb,
    '{"bleu":45,"rare":52,"medium_rare":54,"medium":60}'::jsonb,
    '{"reverse_note":"Le tomahawk est épais : le reverse sear est la méthode idéale. Monte lentement en température au fumoir, puis saisie violente au charbon ou à la fonte brûlante. Repos court, 5-10 min sous aluminium lâche."}'::jsonb,
    5,
    true
  ),

  -- ── PORC ──
  (
    'pulled_pork',
    'Pulled Pork / Pork Butt',
    'porc',
    '🐷',
    'low_and_slow',
    true,
    '[{"temp_c":107,"min_per_kg":264},{"temp_c":121,"min_per_kg":198},{"temp_c":135,"min_per_kg":132}]'::jsonb,
    null,
    12,
    45,
    90,
    null,
    null,
    '{"stall_temp_min":63,"stall_temp_max":74,"wrap_temp_min":70,"wrap_temp_max":76,"begin_test_temp":90,"target_temp_min":93,"target_temp_max":96,"visual_wrap":"La bark est brun foncé, ferme et sèche. Le bone a commencé à dépasser. Si tu passes le doigt sur la bark, elle ne bouge pas. Moment idéal pour emballer.","probe_tender":"L''os tourne librement et se retire presque tout seul. La sonde entre partout sans résistance, comme dans du beurre fondu. C''est prêt à être effiloché."}'::jsonb,
    6,
    true
  ),
  (
    'spare_ribs',
    'Spare Ribs',
    'porc',
    '🍖',
    'low_and_slow',
    true,
    null,
    '{"wrapped":{"min":330,"max":390},"unwrapped":{"min":300,"max":360}}'::jsonb,
    0,
    10,
    20,
    null,
    null,
    '{"visual_wrap":"Les ribs ont pris une belle couleur acajou. La viande a rétréci et les os dépassent d''environ 1-2 cm. La surface est sèche et mate. C''est le bon moment pour emballer avec un peu de jus de pomme ou de miel.","probe_tender":"Flex test : soulève le rack par le milieu avec des pinces. Il doit plier nettement et la surface commencer à se fissurer. La viande se détache de l''os proprement mais ne tombe pas — c''est du competition-style, pas fall-off-the-bone."}'::jsonb,
    7,
    true
  ),
  (
    'baby_back_ribs',
    'Baby Back Ribs',
    'porc',
    '🍖',
    'low_and_slow',
    true,
    null,
    '{"wrapped":{"min":270,"max":330},"unwrapped":{"min":240,"max":300}}'::jsonb,
    0,
    10,
    15,
    null,
    null,
    '{"visual_wrap":"Les baby backs sont plus petits et cuisent plus vite. Emballe quand la couleur est acajou et que les os dépassent bien. Ne sur-cuis pas — elles sèchent plus facilement que des spare ribs.","probe_tender":"Flex test : le rack plie bien et la surface craquelle légèrement. Entre les os, la sonde entre facilement. La viande doit se détacher proprement mais garder de la tenue."}'::jsonb,
    8,
    true
  ),

  -- ── VOLAILLE ──
  (
    'whole_chicken',
    'Poulet entier',
    'volaille',
    '🍗',
    'low_and_slow',
    false,
    '[{"temp_c":110,"min_per_kg":110},{"temp_c":135,"min_per_kg":66},{"temp_c":150,"min_per_kg":55},{"temp_c":165,"min_per_kg":44}]'::jsonb,
    null,
    0,
    10,
    20,
    null,
    null,
    '{"begin_test_temp":65,"target_temp_min":74,"target_temp_max":80,"probe_position":"Plante la sonde dans la partie la plus épaisse de la cuisse, entre le pilon et le haut de cuisse, sans toucher l''os. C''est la dernière zone à atteindre 74°C.","visual_warning":"En dessous de 130°C au fumoir, la peau reste molle et caoutchouteuse. Privilégie 150°C+ si tu veux une peau dorée et croustillante. Astuce pro : finis 10 min à feu vif ou au grill pour crisper la peau."}'::jsonb,
    9,
    true
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  icon = EXCLUDED.icon,
  cook_type = EXCLUDED.cook_type,
  supports_wrap = EXCLUDED.supports_wrap,
  temp_bands = EXCLUDED.temp_bands,
  fixed_times = EXCLUDED.fixed_times,
  wrap_reduction_percent = EXCLUDED.wrap_reduction_percent,
  rest_min = EXCLUDED.rest_min,
  rest_max = EXCLUDED.rest_max,
  reverse_sear = EXCLUDED.reverse_sear,
  doneness_targets = EXCLUDED.doneness_targets,
  cues = EXCLUDED.cues,
  sort_order = EXCLUDED.sort_order,
  is_active = EXCLUDED.is_active;
