-- 029_seed_new_profiles.sql
-- Ajout des profils manquants : agneau (4), porc (2), volaille (3)
-- Données croisées : ThermoWorks, Malcom Reed, Jess Pryles, French Smoker,
-- Le BBQ de Rafa, Bradley Smoker, DuckChar, SmokedBBQSource, AmazingRibs

INSERT INTO cooking_profiles (id, name, category, icon, cook_type, supports_wrap, temp_bands, fixed_times, wrap_reduction_percent, rest_min, rest_max, reverse_sear, doneness_targets, cues, sort_order, is_active)
VALUES
  -- ── AGNEAU ──
  (
    'lamb_shoulder',
    'Épaule d''agneau',
    'agneau',
    '🐑',
    'low_and_slow',
    true,
    '[{"temp_c":107,"min_per_kg":200},{"temp_c":121,"min_per_kg":155},{"temp_c":135,"min_per_kg":110}]'::jsonb,
    null,
    12,
    30,
    60,
    null,
    null,
    '{"stall_temp_min":63,"stall_temp_max":74,"wrap_temp_min":68,"wrap_temp_max":75,"begin_test_temp":88,"target_temp_min":91,"target_temp_max":96,"visual_wrap":"L''os de l''épaule commence à dépasser, la viande a rétréci. La bark est acajou foncé, mate et sèche au toucher. Le gras de surface a rendu. C''est le moment d''emballer — papier boucher de préférence pour garder la bark.","probe_tender":"La sonde entre comme dans du beurre partout dans l''épaule. L''os bouge librement et se retire presque seul. La viande se défait en tirant avec deux fourchettes — c''est prêt pour du pulled lamb."}'::jsonb,
    10,
    true
  ),
  (
    'lamb_leg',
    'Gigot d''agneau',
    'agneau',
    '🐑',
    'low_and_slow',
    false,
    '[{"temp_c":107,"min_per_kg":130},{"temp_c":121,"min_per_kg":100},{"temp_c":135,"min_per_kg":75}]'::jsonb,
    null,
    0,
    15,
    30,
    null,
    null,
    '{"begin_test_temp":52,"target_temp_min":54,"target_temp_max":63,"probe_position":"Plante la sonde au centre de la partie la plus épaisse du gigot, loin de l''os. L''os conduit la chaleur et fausse la mesure.","visual_warning":"Le gigot ne se cuit pas comme un brisket — pas de pulled lamb ici. On vise rosé à cœur (54-60°C). Si tu veux de l''effiloché, prends l''épaule."}'::jsonb,
    11,
    true
  ),
  (
    'lamb_shank',
    'Souris d''agneau',
    'agneau',
    '🐑',
    'low_and_slow',
    true,
    '[{"temp_c":107,"min_per_kg":660},{"temp_c":121,"min_per_kg":540},{"temp_c":135,"min_per_kg":420}]'::jsonb,
    null,
    10,
    15,
    30,
    null,
    null,
    '{"stall_temp_min":65,"stall_temp_max":74,"wrap_temp_min":70,"wrap_temp_max":76,"begin_test_temp":85,"target_temp_min":88,"target_temp_max":96,"visual_wrap":"La viande a rétréci autour de l''os, exposant le bout de l''os. La surface est brun-acajou. C''est le moment d''emballer — ajoute un fond de bouillon ou de jus de pomme dans le papier pour braiser.","probe_tender":"La viande glisse de l''os quand tu soulèves la souris par le bout de l''os. La sonde entre sans résistance dans la partie la plus épaisse. La texture est fondante, presque confite."}'::jsonb,
    12,
    true
  ),
  (
    'rack_of_lamb',
    'Carré d''agneau',
    'agneau',
    '🐑',
    'reverse_sear',
    false,
    '[{"temp_c":107,"min_per_kg":45},{"temp_c":121,"min_per_kg":35},{"temp_c":135,"min_per_kg":25}]'::jsonb,
    null,
    0,
    5,
    10,
    '{"pull_before_target_c":8,"sear_total_minutes_min":2,"sear_total_minutes_max":4}'::jsonb,
    '{"bleu":46,"rare":52,"medium_rare":57,"medium":63}'::jsonb,
    '{"reverse_note":"Le carré d''agneau se fume à basse température (100-120°C) avec du bois fruitier — cerisier ou pommier idéalement. Le chêne et le hickory sont trop forts pour l''agneau. Sors le carré 8°C sous ta cible. Saisie violente 1-2 min par face à 300°C+ pour une croûte dorée."}'::jsonb,
    13,
    true
  ),

  -- ── PORC (compléments) ──
  (
    'pork_belly',
    'Poitrine de porc',
    'porc',
    '🐷',
    'low_and_slow',
    true,
    '[{"temp_c":107,"min_per_kg":264},{"temp_c":121,"min_per_kg":198},{"temp_c":135,"min_per_kg":145}]'::jsonb,
    null,
    12,
    30,
    60,
    null,
    null,
    '{"stall_temp_min":63,"stall_temp_max":74,"wrap_temp_min":71,"wrap_temp_max":77,"begin_test_temp":88,"target_temp_min":93,"target_temp_max":99,"visual_wrap":"La surface de la poitrine est caramélisée, brun foncé à noir. Le gras a commencé à rendre et la couenne (si présente) est croustillante. La viande a visiblement réduit. C''est le moment d''emballer pour la dernière phase de cuisson.","probe_tender":"La sonde entre dans le gras et la viande sans résistance. Si tu secoues la poitrine, elle tremble comme de la gelée. Le gras inter-couches est complètement fondu et translucide. Résultat : fondant en bouche, chaque tranche se tient mais se défait à la fourchette."}'::jsonb,
    14,
    true
  ),
  (
    'pork_tenderloin',
    'Filet mignon de porc',
    'porc',
    '🐷',
    'reverse_sear',
    false,
    '[{"temp_c":107,"min_per_kg":65},{"temp_c":121,"min_per_kg":50},{"temp_c":135,"min_per_kg":38}]'::jsonb,
    null,
    0,
    5,
    10,
    '{"pull_before_target_c":5,"sear_total_minutes_min":2,"sear_total_minutes_max":4}'::jsonb,
    '{"rose":63,"a_point":68,"bien_cuit":74}'::jsonb,
    '{"reverse_note":"Le filet mignon de porc est une pièce très maigre et fine — elle sèche vite. Fume à basse température (110°C) avec du bois fruitier léger (pommier, cerisier). Sors le filet 5°C sous ta cible. Saisie rapide 1 min par face à 250°C+. Ne dépasse jamais 68°C interne pour garder le juteux. En France, le porc se mange rosé (63°C) ou à point (68°C) — jamais saignant."}'::jsonb,
    15,
    true
  ),

  -- ── VOLAILLE (compléments) ──
  (
    'chicken_thighs',
    'Cuisses de poulet',
    'volaille',
    '🍗',
    'low_and_slow',
    false,
    '[{"temp_c":135,"min_per_kg":200},{"temp_c":150,"min_per_kg":130},{"temp_c":165,"min_per_kg":100}]'::jsonb,
    null,
    0,
    5,
    10,
    null,
    null,
    '{"begin_test_temp":65,"target_temp_min":74,"target_temp_max":82,"probe_position":"Plante la sonde dans la partie la plus épaisse de la cuisse, sans toucher l''os. Les cuisses sont plus tolérantes que les blancs — vise 77°C+ pour une texture fondante.","visual_warning":"En dessous de 135°C au fumoir, la peau de poulet reste molle et caoutchouteuse. Fumoir à 150°C+ pour une peau dorée. Astuce compétition : sèche les cuisses au frigo à l''air libre 2h avant de fumer."}'::jsonb,
    16,
    true
  ),
  (
    'turkey_breast',
    'Poitrine de dinde',
    'volaille',
    '🦃',
    'low_and_slow',
    false,
    '[{"temp_c":107,"min_per_kg":100},{"temp_c":121,"min_per_kg":80},{"temp_c":135,"min_per_kg":60}]'::jsonb,
    null,
    0,
    15,
    30,
    null,
    null,
    '{"begin_test_temp":60,"target_temp_min":68,"target_temp_max":74,"probe_position":"Plante la sonde au centre de la partie la plus épaisse de la poitrine, horizontalement. Évite le bord et l''os.","visual_warning":"La dinde absorbe beaucoup de fumée — attention au goût amer si tu utilises du bois fort (mesquite, hickory). Privilégie cerisier, pommier ou érable. Brine la veille (sel + sucre + eau) pour un résultat juteux."}'::jsonb,
    17,
    true
  ),
  (
    'duck_breast',
    'Magret de canard',
    'volaille',
    '🦆',
    'reverse_sear',
    false,
    '[{"temp_c":107,"min_per_kg":55},{"temp_c":121,"min_per_kg":42},{"temp_c":135,"min_per_kg":32}]'::jsonb,
    null,
    0,
    5,
    10,
    '{"pull_before_target_c":5,"sear_total_minutes_min":3,"sear_total_minutes_max":5}'::jsonb,
    '{"bleu":46,"rare":52,"medium_rare":57,"medium":63}'::jsonb,
    '{"reverse_note":"Le magret a une épaisse couche de gras côté peau — score-la en croisillons avant de fumer pour qu''elle rende son gras. Fume côté chair vers le bas à 110°C avec du bois fruitier (cerisier, érable). Sors à 5°C sous ta cible. Saisie côté peau d''abord, 2-3 min sur fonte brûlante pour crisper le gras. Le magret se mange rosé — ne dépasse pas 57°C pour le sweet spot."}'::jsonb,
    18,
    true
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  icon = EXCLUDED.icon,
  cook_type = EXCLUDED.cook_type,
  supports_wrap = EXCLUDED.supports_wrap,
  temp_bands = EXCLUDED.temp_bands,
  fixed_times = EXCLUDED.fixed_times,
  wrap_reduction_percent = EXCLUDED.wrap_reduction_percent,
  rest_min = EXCLUDED.rest_min,
  rest_max = EXCLUDED.rest_max,
  reverse_sear = EXCLUDED.reverse_sear,
  doneness_targets = EXCLUDED.doneness_targets,
  cues = EXCLUDED.cues,
  sort_order = EXCLUDED.sort_order,
  is_active = EXCLUDED.is_active;
