-- 030_recalibrate_profiles.sql
-- Recalibration complète de tous les profils de cuisson
-- Sources croisées : terrain US (Franklin, Meathead, forums) + FR (Bradley Smoker FR, Esprit BBQ, ToutFeuToutFlamme)
-- Audit avril 2026

-- UPSERT tous les profils avec les valeurs recalibrées
INSERT INTO cooking_profiles (id, name, category, icon, cook_type, supports_wrap, temp_bands, fixed_times, wrap_reduction_percent, rest_min, rest_max, reverse_sear, doneness_targets, cues, sort_order, is_active)
VALUES
  -- ── BOEUF ──
  (
    'brisket',
    'Brisket',
    'boeuf',
    '🥩',
    'low_and_slow',
    true,
    '[{"temp_c":107,"min_per_kg":202},{"temp_c":121,"min_per_kg":165},{"temp_c":135,"min_per_kg":120}]'::jsonb,
    null,
    15,
    60,
    120,
    null,
    null,
    '{"stall_temp_min":65,"stall_temp_max":77,"wrap_temp_min":68,"wrap_temp_max":74,"begin_test_temp":90,"target_temp_min":93,"target_temp_max":98,"visual_wrap":"La bark est sombre, sèche au toucher, presque noire. Elle ne se raye plus à l''ongle. Le gras de surface a rendu et s''est figé en une croûte ferme. Si tu hésites, attends encore 15 min — mieux vaut wrapper trop tard que trop tôt.","probe_tender":"La sonde thermique entre comme dans du beurre mou, sans aucune résistance. Teste au point le plus épais du flat. Si ça accroche encore, remets 30 min et reteste."}'::jsonb,
    1,
    true
  ),
  (
    'beef_short_ribs',
    'Beef Short Ribs',
    'boeuf',
    '🥩',
    'low_and_slow',
    true,
    '[{"temp_c":107,"min_per_kg":222},{"temp_c":121,"min_per_kg":168},{"temp_c":135,"min_per_kg":122}]'::jsonb,
    null,
    10,
    30,
    60,
    null,
    null,
    '{"stall_temp_min":65,"stall_temp_max":77,"wrap_temp_min":68,"wrap_temp_max":74,"begin_test_temp":92,"target_temp_min":93,"target_temp_max":99,"visual_wrap":"L''extérieur est bien caramélisé, la bark a viré au brun-noir profond. La viande a rétréci et les os dépassent nettement. C''est le moment.","probe_tender":"La sonde entre entre les fibres avec une résistance minimale. La viande tremble comme de la gelée quand tu secoues légèrement le rack."}'::jsonb,
    2,
    true
  ),
  (
    'chuck_roast',
    'Paleron / Chuck Roast',
    'boeuf',
    '🥩',
    'low_and_slow',
    true,
    '[{"temp_c":107,"min_per_kg":270},{"temp_c":121,"min_per_kg":210},{"temp_c":135,"min_per_kg":150}]'::jsonb,
    null,
    12,
    30,
    60,
    null,
    null,
    '{"stall_temp_min":65,"stall_temp_max":77,"wrap_temp_min":71,"wrap_temp_max":77,"begin_test_temp":91,"target_temp_min":91,"target_temp_max":96,"visual_wrap":"La bark est bien formée, couleur acajou à brun foncé. Le morceau a visiblement réduit de volume. Le gras de surface a rendu.","probe_tender":"La sonde entre sans résistance franche. La viande se défait facilement en tirant avec deux fourchettes — c''est prêt pour du pulled beef."}'::jsonb,
    3,
    true
  ),
  (
    'prime_rib',
    'Côte de bœuf',
    'boeuf',
    '🥩',
    'reverse_sear',
    false,
    '[{"temp_c":107,"min_per_kg":48},{"temp_c":121,"min_per_kg":38},{"temp_c":135,"min_per_kg":27}]'::jsonb,
    null,
    0,
    10,
    20,
    '{"pull_before_target_c":8,"sear_total_minutes_min":3,"sear_total_minutes_max":6}'::jsonb,
    '{"bleu":45,"rare":52,"medium_rare":54,"medium":60}'::jsonb,
    '{"reverse_note":"Place la côte en zone indirecte à 110°C avec des copeaux de bois. Ferme le couvercle et surveille la sonde. Sors la viande 8°C sous ta cible. Saisie violente 1-2 min par face à 250°C+. Repos 10 min sous alu lâche."}'::jsonb,
    4,
    true
  ),
  (
    'tomahawk',
    'Tomahawk / steak épais',
    'boeuf',
    '🥩',
    'reverse_sear',
    false,
    '[{"temp_c":107,"min_per_kg":58},{"temp_c":121,"min_per_kg":46},{"temp_c":135,"min_per_kg":33}]'::jsonb,
    null,
    0,
    5,
    10,
    '{"pull_before_target_c":6,"sear_total_minutes_min":3,"sear_total_minutes_max":6}'::jsonb,
    '{"bleu":45,"rare":52,"medium_rare":54,"medium":60}'::jsonb,
    '{"reverse_note":"Le tomahawk est épais : le reverse sear est la méthode idéale. Monte lentement en température au fumoir, puis saisie violente au charbon ou à la fonte brûlante. Repos court, 5-10 min sous aluminium lâche."}'::jsonb,
    5,
    true
  ),

  -- ── PORC ──
  (
    'pulled_pork',
    'Pulled Pork / Pork Butt',
    'porc',
    '🐷',
    'low_and_slow',
    true,
    '[{"temp_c":107,"min_per_kg":212},{"temp_c":121,"min_per_kg":180},{"temp_c":135,"min_per_kg":140}]'::jsonb,
    null,
    12,
    45,
    90,
    null,
    null,
    '{"stall_temp_min":63,"stall_temp_max":74,"wrap_temp_min":70,"wrap_temp_max":76,"begin_test_temp":90,"target_temp_min":93,"target_temp_max":96,"visual_wrap":"La bark est brun foncé, ferme et sèche. Le bone a commencé à dépasser. Si tu passes le doigt sur la bark, elle ne bouge pas. Moment idéal pour emballer.","probe_tender":"L''os tourne librement et se retire presque tout seul. La sonde entre partout sans résistance, comme dans du beurre fondu. C''est prêt à être effiloché."}'::jsonb,
    6,
    true
  ),
  (
    'spare_ribs',
    'Spare Ribs',
    'porc',
    '🍖',
    'low_and_slow',
    true,
    null,
    '{"wrapped":{"min":330,"max":390},"unwrapped":{"min":300,"max":360}}'::jsonb,
    0,
    10,
    20,
    null,
    null,
    '{"visual_wrap":"Les ribs ont pris une belle couleur acajou. La viande a rétréci et les os dépassent d''environ 1-2 cm. La surface est sèche et mate. C''est le bon moment pour emballer avec un peu de jus de pomme ou de miel.","probe_tender":"Flex test : soulève le rack par le milieu avec des pinces. Il doit plier nettement et la surface commencer à se fissurer. La viande se détache de l''os proprement mais ne tombe pas — c''est du competition-style, pas fall-off-the-bone."}'::jsonb,
    7,
    true
  ),
  (
    'baby_back_ribs',
    'Baby Back Ribs',
    'porc',
    '🍖',
    'low_and_slow',
    true,
    null,
    '{"wrapped":{"min":270,"max":330},"unwrapped":{"min":240,"max":300}}'::jsonb,
    0,
    10,
    15,
    null,
    null,
    '{"visual_wrap":"Les baby backs sont plus petits et cuisent plus vite. Emballe quand la couleur est acajou et que les os dépassent bien. Ne sur-cuis pas — elles sèchent plus facilement que des spare ribs.","probe_tender":"Flex test : le rack plie bien et la surface craquelle légèrement. Entre les os, la sonde entre facilement. La viande doit se détacher proprement mais garder de la tenue."}'::jsonb,
    8,
    true
  ),
  (
    'pork_belly',
    'Poitrine de porc',
    'porc',
    '🐷',
    'low_and_slow',
    true,
    '[{"temp_c":107,"min_per_kg":182},{"temp_c":121,"min_per_kg":148},{"temp_c":135,"min_per_kg":110}]'::jsonb,
    null,
    12,
    30,
    60,
    null,
    null,
    '{"stall_temp_min":63,"stall_temp_max":74,"wrap_temp_min":71,"wrap_temp_max":77,"begin_test_temp":88,"target_temp_min":93,"target_temp_max":99,"visual_wrap":"La surface de la poitrine est caramélisée, brun foncé à noir. Le gras a commencé à rendre et la couenne (si présente) est croustillante. La viande a visiblement réduit. C''est le moment d''emballer pour la dernière phase de cuisson.","probe_tender":"La sonde entre dans le gras et la viande sans résistance. Si tu secoues la poitrine, elle tremble comme de la gelée. Le gras inter-couches est complètement fondu et translucide."}'::jsonb,
    9,
    true
  ),
  (
    'pork_tenderloin',
    'Filet mignon de porc',
    'porc',
    '🐷',
    'reverse_sear',
    false,
    '[{"temp_c":107,"min_per_kg":55},{"temp_c":121,"min_per_kg":42},{"temp_c":135,"min_per_kg":31}]'::jsonb,
    null,
    0,
    5,
    10,
    '{"pull_before_target_c":5,"sear_total_minutes_min":2,"sear_total_minutes_max":4}'::jsonb,
    '{"rose":63,"a_point":68,"bien_cuit":74}'::jsonb,
    '{"reverse_note":"Le filet mignon de porc est une pièce très maigre et fine — elle sèche vite. Fume à basse température (110°C) avec du bois fruitier léger (pommier, cerisier). Sors le filet 5°C sous ta cible. Saisie rapide 1 min par face à 250°C+. Ne dépasse jamais 68°C interne pour garder le juteux."}'::jsonb,
    10,
    true
  ),

  -- ── VOLAILLE ──
  (
    'whole_chicken',
    'Poulet entier',
    'volaille',
    '🍗',
    'low_and_slow',
    false,
    '[{"temp_c":110,"min_per_kg":115},{"temp_c":135,"min_per_kg":86},{"temp_c":150,"min_per_kg":62},{"temp_c":165,"min_per_kg":48}]'::jsonb,
    null,
    0,
    10,
    20,
    null,
    null,
    '{"begin_test_temp":65,"target_temp_min":74,"target_temp_max":80,"probe_position":"Plante la sonde dans la partie la plus épaisse de la cuisse, entre le pilon et le haut de cuisse, sans toucher l''os. C''est la dernière zone à atteindre 74°C.","visual_warning":"En dessous de 130°C au fumoir, la peau reste molle et caoutchouteuse. Privilégie 150°C+ si tu veux une peau dorée et croustillante."}'::jsonb,
    11,
    true
  ),
  (
    'chicken_thighs',
    'Cuisses de poulet',
    'volaille',
    '🍗',
    'low_and_slow',
    false,
    '[{"temp_c":135,"min_per_kg":100},{"temp_c":150,"min_per_kg":70},{"temp_c":165,"min_per_kg":52}]'::jsonb,
    null,
    0,
    5,
    10,
    null,
    null,
    '{"begin_test_temp":65,"target_temp_min":74,"target_temp_max":82,"probe_position":"Plante la sonde dans la partie la plus épaisse de la cuisse, sans toucher l''os. Les cuisses sont plus tolérantes que les blancs — vise 77°C+ pour une texture fondante.","visual_warning":"En dessous de 135°C au fumoir, la peau de poulet reste molle et caoutchouteuse. Fumoir à 150°C+ pour une peau dorée."}'::jsonb,
    12,
    true
  ),
  (
    'turkey_breast',
    'Poitrine de dinde',
    'volaille',
    '🦃',
    'low_and_slow',
    false,
    '[{"temp_c":107,"min_per_kg":118},{"temp_c":121,"min_per_kg":100},{"temp_c":135,"min_per_kg":72}]'::jsonb,
    null,
    0,
    15,
    30,
    null,
    null,
    '{"begin_test_temp":60,"target_temp_min":68,"target_temp_max":74,"probe_position":"Plante la sonde au centre de la partie la plus épaisse de la poitrine, horizontalement. Évite le bord et l''os.","visual_warning":"La dinde absorbe beaucoup de fumée — attention au goût amer si tu utilises du bois fort (mesquite, hickory). Privilégie cerisier, pommier ou érable. Brine la veille pour un résultat juteux."}'::jsonb,
    13,
    true
  ),
  (
    'duck_breast',
    'Magret de canard',
    'volaille',
    '🦆',
    'reverse_sear',
    false,
    '[{"temp_c":107,"min_per_kg":45},{"temp_c":121,"min_per_kg":34},{"temp_c":135,"min_per_kg":25}]'::jsonb,
    null,
    0,
    5,
    10,
    '{"pull_before_target_c":5,"sear_total_minutes_min":3,"sear_total_minutes_max":5}'::jsonb,
    '{"rose":54,"a_point":58,"bien_cuit":65}'::jsonb,
    '{"reverse_note":"Le magret a une épaisse couche de gras côté peau — score-la en croisillons avant de fumer pour qu''elle rende son gras. Fume côté chair vers le bas à 110°C avec du bois fruitier (cerisier, érable). Sors à 5°C sous ta cible. Saisie côté peau d''abord, 2-3 min sur fonte brûlante pour crisper le gras. Le magret se mange rosé (54°C)."}'::jsonb,
    14,
    true
  ),

  -- ── AGNEAU ──
  (
    'lamb_shoulder',
    'Épaule d''agneau',
    'agneau',
    '🐑',
    'low_and_slow',
    true,
    '[{"temp_c":107,"min_per_kg":198},{"temp_c":121,"min_per_kg":162},{"temp_c":135,"min_per_kg":120}]'::jsonb,
    null,
    12,
    30,
    60,
    null,
    null,
    '{"stall_temp_min":63,"stall_temp_max":74,"wrap_temp_min":68,"wrap_temp_max":75,"begin_test_temp":88,"target_temp_min":91,"target_temp_max":96,"visual_wrap":"L''os de l''épaule commence à dépasser, la viande a rétréci. La bark est acajou foncé, mate et sèche au toucher. Le gras de surface a rendu. C''est le moment d''emballer — papier boucher de préférence pour garder la bark.","probe_tender":"La sonde entre comme dans du beurre partout dans l''épaule. L''os bouge librement et se retire presque seul. La viande se défait en tirant avec deux fourchettes — c''est prêt pour du pulled lamb."}'::jsonb,
    15,
    true
  ),
  (
    'lamb_leg',
    'Gigot d''agneau',
    'agneau',
    '🐑',
    'low_and_slow',
    false,
    '[{"temp_c":107,"min_per_kg":115},{"temp_c":121,"min_per_kg":94},{"temp_c":135,"min_per_kg":71}]'::jsonb,
    null,
    0,
    15,
    30,
    null,
    null,
    '{"begin_test_temp":52,"target_temp_min":54,"target_temp_max":63,"probe_position":"Plante la sonde au centre de la partie la plus épaisse du gigot, loin de l''os. L''os conduit la chaleur et fausse la mesure.","visual_warning":"Le gigot ne se cuit pas comme un brisket — pas de pulled lamb ici. On vise rosé à cœur (54-60°C). Si tu veux de l''effiloché, prends l''épaule."}'::jsonb,
    16,
    true
  ),
  (
    'lamb_shank',
    'Souris d''agneau',
    'agneau',
    '🐑',
    'low_and_slow',
    true,
    '[{"temp_c":107,"min_per_kg":660},{"temp_c":121,"min_per_kg":540},{"temp_c":135,"min_per_kg":420}]'::jsonb,
    null,
    10,
    15,
    30,
    null,
    null,
    '{"stall_temp_min":65,"stall_temp_max":74,"wrap_temp_min":70,"wrap_temp_max":76,"begin_test_temp":85,"target_temp_min":88,"target_temp_max":96,"visual_wrap":"La viande a rétréci autour de l''os, exposant le bout de l''os. La surface est brun-acajou. C''est le moment d''emballer — ajoute un fond de bouillon ou de jus de pomme dans le papier pour braiser.","probe_tender":"La viande glisse de l''os quand tu soulèves la souris par le bout de l''os. La sonde entre sans résistance dans la partie la plus épaisse. La texture est fondante, presque confite."}'::jsonb,
    17,
    true
  ),
  (
    'rack_of_lamb',
    'Carré d''agneau',
    'agneau',
    '🐑',
    'reverse_sear',
    false,
    '[{"temp_c":107,"min_per_kg":50},{"temp_c":121,"min_per_kg":40},{"temp_c":135,"min_per_kg":31}]'::jsonb,
    null,
    0,
    5,
    10,
    '{"pull_before_target_c":8,"sear_total_minutes_min":2,"sear_total_minutes_max":4}'::jsonb,
    '{"bleu":46,"rare":52,"medium_rare":57,"medium":63}'::jsonb,
    '{"reverse_note":"Le carré d''agneau se fume à basse température (100-120°C) avec du bois fruitier — cerisier ou pommier idéalement. Le chêne et le hickory sont trop forts pour l''agneau. Sors le carré 8°C sous ta cible. Saisie violente 1-2 min par face à 300°C+ pour une croûte dorée."}'::jsonb,
    18,
    true
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  icon = EXCLUDED.icon,
  cook_type = EXCLUDED.cook_type,
  supports_wrap = EXCLUDED.supports_wrap,
  temp_bands = EXCLUDED.temp_bands,
  fixed_times = EXCLUDED.fixed_times,
  wrap_reduction_percent = EXCLUDED.wrap_reduction_percent,
  rest_min = EXCLUDED.rest_min,
  rest_max = EXCLUDED.rest_max,
  reverse_sear = EXCLUDED.reverse_sear,
  doneness_targets = EXCLUDED.doneness_targets,
  cues = EXCLUDED.cues,
  sort_order = EXCLUDED.sort_order,
  is_active = EXCLUDED.is_active,
  updated_at = now();
