export const CALCULATOR_REFERENCE_SCENARIOS = [
  {
    id: 'brisket_ls_nowrap',
    meatKey: 'brisket',
    weightKg: 7,
    options: {
      method: 'low_and_slow',
      smokerTempC: 121,
      smokerType: 'offset',
      wrapType: 'none',
      marbling: 'medium',
      thicknessCm: 11,
      serveTime: '19:00',
    },
  },
  {
    id: 'brisket_ls_paper',
    meatKey: 'brisket',
    weightKg: 7,
    options: {
      method: 'low_and_slow',
      smokerTempC: 121,
      smokerType: 'offset',
      wrapType: 'butcher_paper',
      marbling: 'medium',
      thicknessCm: 11,
      serveTime: '19:00',
    },
  },
  {
    id: 'pork_shoulder_ls',
    meatKey: 'pork_shoulder',
    weightKg: 4.5,
    options: {
      method: 'low_and_slow',
      smokerTempC: 121,
      smokerType: 'kamado',
      wrapType: 'none',
      marbling: 'medium',
      thicknessCm: 10,
      serveTime: '19:00',
    },
  },
  {
    id: 'spare_ribs_fixed',
    meatKey: 'ribs_pork',
    weightKg: 2,
    options: {
      method: 'low_and_slow',
      smokerTempC: 110,
      smokerType: 'kettle',
      wrapType: 'foil',
      marbling: 'medium',
      thicknessCm: 4,
      serveTime: '19:00',
    },
  },
  {
    id: 'baby_back_fixed',
    meatKey: 'ribs_baby_back',
    weightKg: 1.6,
    options: {
      method: 'low_and_slow',
      smokerTempC: 110,
      smokerType: 'kettle',
      wrapType: 'foil',
      marbling: 'medium',
      thicknessCm: 3.5,
      serveTime: '19:00',
    },
  },
  {
    id: 'beef_ribs_hot',
    meatKey: 'ribs_beef',
    weightKg: 3.5,
    options: {
      method: 'hot_and_fast',
      smokerTempC: 141,
      smokerType: 'offset',
      wrapType: 'none',
      marbling: 'high',
      thicknessCm: 8,
      serveTime: '19:00',
    },
  },
  {
    id: 'paleron_ls',
    meatKey: 'paleron',
    weightKg: 2.2,
    options: {
      method: 'low_and_slow',
      smokerTempC: 121,
      smokerType: 'pellet',
      wrapType: 'butcher_paper',
      marbling: 'medium',
      thicknessCm: 7,
      serveTime: '19:00',
    },
  },
  {
    id: 'lamb_shoulder_ls',
    meatKey: 'lamb_shoulder',
    weightKg: 3.5,
    options: {
      method: 'low_and_slow',
      smokerTempC: 121,
      smokerType: 'kamado',
      wrapType: 'butcher_paper',
      marbling: 'medium',
      thicknessCm: 8,
      serveTime: '19:00',
    },
  },
  {
    id: 'whole_chicken_hot',
    meatKey: 'whole_chicken',
    weightKg: 1.8,
    options: {
      method: 'hot_and_fast',
      smokerTempC: 149,
      smokerType: 'pellet',
      wrapType: 'none',
      marbling: 'medium',
      thicknessCm: 5,
      serveTime: '19:00',
    },
  },
  {
    id: 'lamb_leg_medium',
    meatKey: 'lamb_leg',
    weightKg: 2.5,
    options: {
      method: 'hot_and_fast',
      smokerTempC: 135,
      smokerType: 'kettle',
      wrapType: 'none',
      marbling: 'medium',
      thicknessCm: 7,
      serveTime: '19:00',
      lambLegStyle: 'medium',
    },
  },
  {
    id: 'lamb_leg_pulled',
    meatKey: 'lamb_leg',
    weightKg: 2.5,
    options: {
      method: 'low_and_slow',
      smokerTempC: 121,
      smokerType: 'kettle',
      wrapType: 'foil',
      marbling: 'medium',
      thicknessCm: 7,
      serveTime: '19:00',
      lambLegStyle: 'pulled',
    },
  },
]
